"""What the public demo opens on.

A visitor arriving at the demo should land on
an event that has already happened to somebody: a roster with photographs, a
preliminary round that was raced, standings that mean something, and a final
whose field filled itself from those standings.

An empty race would show the least interesting version of the app — the part
an evaluator can already imagine — and would put the work of making it
interesting on them.

Built from code, not from an archive
------------------------------------
The plan was to bake a backup archive into the image and restore it at boot,
so that reset could reuse ``restore_archive``'s teardown. Seeding is written
here instead, for three reasons:

* at boot there is nothing to tear down. The careful part of a restore — stop
  the timer managers whose track ids are about to change, dispose the pool
  before the file is swapped — exists because a restore replaces a *running*
  event. A fresh container has no such thing;
* an archive is a binary committed to the repository, regenerated by hand
  whenever the demo should show something different, and stale by default;
* seeding from code is always at the current schema, so there is no revision
  check to satisfy and no upgrade to run afterwards.

The reset half of that stage is a separate question and is deliberately not
here — on the deploy target the instance is ephemeral, so scale-to-zero *is*
the reset. An always-on host would need a timer instead: see
https://github.com/dknowles2/trusty-track/issues/297.

Repeatable
----------
Every invented value comes through :mod:`backend.demo_seed`, keyed on the
thing being invented rather than drawn from a running sequence. Set
``TRUSTYTRACK_DEMO_SEED`` on the deployment and every visitor sees the same
roster and the same times — which for a demo is the point, where for an
operator it would read as the app being broken.
"""

import logging

from sqlalchemy.orm import Session

from backend import demo_seed
from backend.db import crud, models, schemas
from backend.domain import audit, lanes

logger = logging.getLogger(__name__)

#: What the demo's organisation is called. It is on screen throughout, so it
#: says what this is rather than naming a pack that does not exist.
DEMO_ORGANIZATION_NAME = "Trusty Track Demo"

#: The demo's track. Four lanes is the common club setup and what every
#: screenshot in the documentation shows.
DEMO_TRACK_NAME = "Demo Track"
DEMO_LANE_COUNT = 4

#: The window a car's time is drawn from, in seconds. A real forty-foot track
#: puts a well-built car around three seconds; the spread is wide enough that
#: the standings have a story in them and narrow enough to stay plausible.
_FASTEST = 2.85
_SLOWEST = 3.65


def is_seeded(db: Session) -> bool:
    """Whether this database already holds a demo.

    Asks about the ``Organization``, which is what the first-run gate asks about: an
    install is configured exactly when one exists. That makes seeding idempotent
    without a marker column — and a marker column is the thing #201 declined
    for the practice race, for the same reason. Nothing else branches on it.
    """
    return db.query(models.Organization).first() is not None


def seed(db: Session) -> models.Race:
    """Configure the system and race most of a practice event.

    Returns the race, so a caller can log which one it made.
    """
    crud.create_initial_config(
        db,
        schemas.InitialConfigCreate(
            organization_name=DEMO_ORGANIZATION_NAME,
            tracks=[
                schemas.TrackCreate(
                    name=DEMO_TRACK_NAME,
                    lane_count=DEMO_LANE_COUNT,
                    timer_type=models.TimerType.FAKE,
                )
            ],
        ),
    )
    db.commit()

    race = crud.create_practice_race(db)
    _race_the_preliminaries(db, race)
    return race


def _race_the_preliminaries(db: Session, race: models.Race) -> None:
    """Record a result for every heat of the first round, and stop there.

    **The final is left unraced on purpose**, and that is the whole shape of
    the demo's opening state. Racing everything would leave a visitor with
    nothing to do but read; racing nothing would show an empty leaderboard.
    Racing the preliminaries and stopping gives all three of the things worth
    seeing at once: standings drawn from real results, a championship field
    that filled itself through the advancement cascade, and a heat still on the
    schedule that the visitor can run themselves.
    """
    rounds = sorted(
        (r for r in crud.get_rounds(db, race.id) if r.advancement_source is None),
        key=lambda r: r.round_number,
    )
    if not rounds:  # pragma: no cover - create_practice_race always makes one
        logger.warning("The demo race has no preliminary round to race.")
        return

    prelim = rounds[0]
    for heat in crud.get_heats(db, race.id, round_id=prelim.id):
        crud.record_heat_result(
            db,
            heat.id,
            _results_for(db, heat, race.name),
            source=audit.ResultSource.TIMER,
        )


def _results_for(db: Session, heat: models.Heat, race_name: str) -> list[lanes.Lane]:
    """Invented times for one heat, with places derived from them.

    Keyed on the race's *name* and the heat's number rather than on either id:
    an id depends on how much else the process created first, so keying on one
    would give the same demo different times depending on what ran before it.
    That is `demo_seed`'s standing rule.
    """
    generator = demo_seed.generator(f"demo heat:{race_name}:{heat.heat_number}")

    raced = []
    empty = []
    for lane in crud.heat_lanes_of(db, heat):
        if lane.racer_id is None:
            # An unused lane of a short heat, or a championship slot nobody has
            # advanced into. Neither gets a time; both keep their row.
            empty.append(lane)
        else:
            raced.append(
                lanes.Lane(
                    lane=lane.lane,
                    racer_id=lane.racer_id,
                    time=round(generator.uniform(_FASTEST, _SLOWEST), 3),
                )
            )

    ordered = sorted(raced, key=lambda lane: lane.time)
    placed = [
        lanes.Lane(lane=lane.lane, racer_id=lane.racer_id, time=lane.time, place=place)
        for place, lane in enumerate(ordered, start=1)
    ]
    return sorted(placed + empty, key=lambda lane: lane.lane)
