"""``perfect_n_tables.py`` itself (#1090, part C).

`test_domain_scheduling.py`'s PERFECT_N section already checks the property
that matters through the real scheduling path — `generate_perfect_n`'s
output, id-mapped and lane-mapped, meets a constant number of times for
every pair. This file checks the *table data* directly: its own structural
shape, and the split between "true Perfect-N" and (were one ever added)
"lane-perfect only" the module docstring promises.

**No DerbyNet fixture comparison lives here.** #1090's brief asks for one
(`test_transcription_matches_derbynet_where_both_exist`, with DerbyNet's
rows embedded as attributed fixture data) contingent on DerbyNet's licence
permitting it. It does not: `jeffpiazza/derbynet`'s GitHub-detected licence
is `NOASSERTION` (checked during this PR via `gh api repos/jeffpiazza/
derbynet --jq .license`), meaning no licence is declared and the default
"all rights reserved" applies — vendoring its generator tables into this
repo's test fixtures is not something that licence permits. Per the brief's
own fallback for exactly this case, the comparison instead lives in two
places that do not require embedding DerbyNet's data: the PR body (a
results table, generated by running the script below once, by hand, during
review) and `scripts/compare_perfect_n_with_derbynet.py`, which fetches
DerbyNet's generator source directly over the network at run time — not
part of this suite or of CI, since pytest here must not depend on network
access.
"""

from __future__ import annotations

import itertools

from backend.domain.schedulers.perfect_n_tables import TABLES, TRUE_PERFECT


def test_every_table_names_a_lanes_and_n_at_least_as_big_as_lanes():
    """No table covers a field smaller than the track — see
    `perfect_n.available_for`'s own docstring for why: a published Perfect-N
    chart assumes a full field, unlike PPC/ROTATION's graceful degrade.
    """
    for lanes, n in TABLES:
        assert lanes >= 3, f"({lanes}, {n}): no table should exist below 3 lanes"
        assert n >= lanes, f"({lanes}, {n}): field smaller than the track"


def test_every_table_has_exactly_n_heats_of_exactly_lanes_positions():
    for (lanes, n), rows in TABLES.items():
        assert len(rows) == n, f"({lanes}, {n}): {len(rows)} heats, expected {n}"
        for row in rows:
            assert len(row) == lanes, f"({lanes}, {n}): heat with {len(row)} lanes"
            assert len(set(row)) == lanes, f"({lanes}, {n}): a heat repeats a car"
            assert set(row) <= set(range(1, n + 1)), (
                f"({lanes}, {n}): a car number outside 1..{n}"
            )


def test_every_table_gives_every_car_every_lane_exactly_once():
    for (lanes, n), rows in TABLES.items():
        lane_of: dict[int, set[int]] = {car: set() for car in range(1, n + 1)}
        for row in rows:
            for lane_index, car in enumerate(row):
                assert (lane_index + 1) not in lane_of[car], (
                    f"({lanes}, {n}): car {car} repeats lane {lane_index + 1}"
                )
                lane_of[car].add(lane_index + 1)
        for car, seen in lane_of.items():
            assert seen == set(range(1, lanes + 1)), (
                f"({lanes}, {n}): car {car} ran lanes {sorted(seen)}, "
                f"expected 1..{lanes}"
            )


def test_true_perfect_tables_have_a_constant_pairwise_meeting_count():
    """`TRUE_PERFECT` is every table this module ships (see its own
    docstring) — this is the guarantee that name promises, checked directly
    against the raw chart data rather than through a scheduled/shuffled
    `HeatPlan` (which `test_domain_scheduling.py` already covers).
    """
    assert frozenset(TABLES) == TRUE_PERFECT, (
        "TRUE_PERFECT and TABLES have drifted apart — a table added without "
        "being added to (or deliberately left out of) TRUE_PERFECT"
    )
    for lanes, n in TRUE_PERFECT:
        rows = TABLES[(lanes, n)]
        meetings: dict[tuple[int, int], int] = {}
        for row in rows:
            for a, b in itertools.combinations(sorted(row), 2):
                meetings[(a, b)] = meetings.get((a, b), 0) + 1
        total_pairs = n * (n - 1) // 2
        assert len(meetings) == total_pairs, (
            f"({lanes}, {n}): {len(meetings)} pairs met at least once, "
            f"expected all {total_pairs}"
        )
        assert len(set(meetings.values())) == 1, (
            f"({lanes}, {n}) is claimed TRUE_PERFECT but its meeting counts "
            f"vary: {sorted(set(meetings.values()))}"
        )
