/**
 * Race day, end to end: a real backend, a real browser, a real timer path.
 *
 * The rules these tests cross are each well covered by a unit test — the PPC
 * scheduler in `test_domain_scheduling.py`, scoring in `domain/scoring.py`,
 * advancement in `domain/advancement.py`. What is not covered anywhere else is
 * that those answers still arrive intact after a GraphQL round trip and a pass
 * through the normalized cache, which is precisely where a #12-era bug lives:
 * the payload is well formed, the rule is right, and the screen shows nothing.
 *
 * Deliberately one test per question, each seeding its own race. The docs
 * screenshot specs are a single long `test()` where every step depends on the
 * last, and a break a third of the way through looked for months like a spec
 * that ran (#114). Splitting costs a few seconds of setup and buys a failure
 * that names itself.
 *
 * Run with:
 *   cd frontend && npm run test:e2e
 */

import { test, expect } from '@playwright/test';
import {
    BACKEND_URL,
    createSchedule,
    dismissRoundSummary,
    ensureConfigured,
    gql,
    RACERS,
    readHeats,
    readRounds,
    recordRound,
    seedRace,
} from './support';

test('the wizard generates a schedule that fills every lane', async ({ page }) => {
    // #26: greedy lane filling finds a maximal matching, not a maximum one, and
    // used to strand a lane in roughly one in four four-lane schedules — which
    // under POINTS scoring made the short-changed racer's score *better*. The
    // property is held by `test_domain_scheduling.py`; this is the same claim
    // made about a schedule the operator actually generated by clicking.
    const { raceId, laneCount, racers } = await seedRace(page, 'Race Day Schedule');

    await page.goto(`/race/${raceId}/control`);
    await page.getByRole('button', { name: /Start Round Creation Wizard/i }).click();
    await expect(page.getByRole('heading', { name: 'Race Schedule Wizard' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Generate schedule' }).click();

    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    // The wizard's own defaults add a championship round, whose lanes are
    // undecided slots rather than racers. This claim is about the preliminary
    // round, where the field is the roster.
    const prelim = (await readRounds(page, raceId)).find((r) => r.advancementSource === null)!;
    const heats = (await readHeats(page, raceId)).filter((h) => h.roundId === prelim.id);

    // Lane 1 is seeded with every racer, which fixes the heat count.
    expect(heats).toHaveLength(racers.length);
    for (const heat of heats) {
        expect(heat.lanes.filter((l) => l.racerId !== null)).toHaveLength(laneCount);
    }

    // Every racer therefore runs once per lane, and nobody runs a heat fewer.
    const appearances = new Map(racers.map((r) => [r.id, 0]));
    for (const heat of heats) {
        for (const lane of heat.lanes) {
            if (lane.racerId !== null) {
                appearances.set(lane.racerId, appearances.get(lane.racerId)! + 1);
            }
        }
    }
    expect([...appearances.values()]).toEqual(racers.map(() => laneCount));
});

test('a heat run on the timer records times that survive a reload', async ({ page }) => {
    // The whole timer path: arming over a subscription, the fake device driving
    // `TimerManager` through the same code a serial one does, the result
    // reaching the database, and the screen showing the stored record rather
    // than the pending times it was showing a moment earlier (#7).
    const { raceId, laneCount } = await seedRace(page, 'Race Day Timer');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    // No lane has a time before the heat is run — otherwise the assertion below
    // would pass against a heat that was already recorded.
    const times = page.getByText(/^\d+\.\d{3}s$/);
    await expect(times).toHaveCount(0);

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    await expect(times).toHaveCount(laneCount, { timeout: 30000 });

    // A time on screen is not yet a stored result: until `record_heat_result`
    // runs it is the manager's pending state, and an abort still loses it. The
    // schedule is where a fresh page load shows the record — the execution view
    // moves on to the first heat still to be run, which is the next one.
    await page.goto(`/race/${raceId}/control`);
    await expect(times).toHaveCount(laneCount, { timeout: 30000 });

    const [heat] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    const run = heat.lanes.filter((l) => l.racerId !== null);
    expect(run.map((l) => l.time).every((t) => t !== null)).toBe(true);
    expect([...run].map((l) => l.place).sort((a, b) => a! - b!)).toEqual(
        Array.from({ length: laneCount }, (_, i) => i + 1),
    );
});

test('standings arrive over the subscription without a reload', async ({ page }) => {
    // The leaderboard is subscription-fed, so this is the one path where a
    // typed payload landing in the normalized cache is the whole feature (#12).
    // A query-backed version of this test would pass with the subscription
    // broken.
    const { raceId, racers } = await seedRace(page, 'Race Day Standings');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/standings`);
    await expect(page.getByText('No results yet')).toBeVisible({ timeout: 30000 });

    const heats = await readHeats(page, raceId);
    await recordRound(page, heats, racers);

    // No reload: if the row appears, the subscription delivered it.
    const rows = page.getByRole('row');
    await expect(rows.filter({ hasText: 'Ada Ant' })).toBeVisible({ timeout: 30000 });

    // Car number decides the times `recordRound` writes, so the standings are
    // the roster in car-number order.
    const names = await page.getByRole('row').allInnerTexts();
    const ranked = names
        .slice(1)
        .map((row) => row.split('\t').find((cell) => /\w+ \w+/.test(cell)));
    expect(ranked.slice(0, 3)).toEqual(['Ada Ant', 'Ben Bear', 'Cy Cat']);

    // Everyone ran every heat of the round, so nobody is short.
    for (const row of await rows.all()) {
        const text = await row.innerText();
        if (text.includes('Rank')) continue;
        expect(text).not.toContain('\t-\t');
    }
});

test('finishing the prelims fills the championship round with the top finishers', async ({
    page,
}) => {
    // `record_heat_result` re-runs advancement on every result, so a final's
    // field is decided by the cascade rather than by an operator action. Until
    // it fires the round holds placeholders and `phase` reports NOT_READY,
    // which leaves the operator screen with no controls at all.
    const { raceId, racers } = await seedRace(page, 'Race Day Championship');
    await createSchedule(page, raceId, { name: 'Pack Final', numTopRacers: 3 });

    const rounds = await readRounds(page, raceId);
    const prelim = rounds.find((r) => r.advancementSource === null)!;
    const final = rounds.find((r) => r.advancementSource !== null)!;

    // Before any result, the final's lanes are undecided slots.
    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Placeholder 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    const heats = await readHeats(page, raceId);
    await recordRound(
        page,
        heats.filter((h) => h.roundId === prelim.id),
        racers,
    );

    await page.reload();
    await dismissRoundSummary(page);

    for (const name of ['Ada Ant', 'Ben Bear', 'Cy Cat']) {
        await expect(page.getByText(`${name} (#`, { exact: false }).first()).toBeVisible({
            timeout: 30000,
        });
    }
    await expect(page.getByText('Placeholder 1', { exact: true })).toHaveCount(0);

    const finalHeats = (await readHeats(page, raceId)).filter((h) => h.roundId === final.id);
    const fielded = new Set(
        finalHeats.flatMap((h) => h.lanes.map((l) => l.racerId).filter((id) => id !== null)),
    );
    expect([...fielded].sort((a, b) => a! - b!)).toEqual(
        racers
            .filter((r) => r.carNumber <= 3)
            .map((r) => r.id)
            .sort((a, b) => a - b),
    );
});

test('the last heat of the race raises a summary pointing at standings, awards and printing (#847)', async ({
    page,
}) => {
    // The reported dead end: the last heat lands and On Deck says "Race
    // Complete!" with nothing pointing anywhere. The modal has to be seen
    // live, not recovered after a reload — a race that finished before the
    // screen opened must not throw up a celebration on load, the same
    // `seen === null` rule `roundCompletion.ts` already needed for the round
    // summary (`raceCompletion.ts` here).
    // The final's field is exactly the lane count, so every lane the round
    // schedules holds a racer — `recordRound` sends only occupied lanes,
    // and a final short a lane (fewer top racers than lanes) would need a
    // second helper to fill the rest in as unraced.
    const { raceId, racers, laneCount } = await seedRace(page, 'Race Day Finish');
    await createSchedule(page, raceId, { name: 'Pack Final', numTopRacers: laneCount });

    const rounds = await readRounds(page, raceId);
    const prelim = rounds.find((r) => r.advancementSource === null)!;
    const final = rounds.find((r) => r.advancementSource !== null)!;

    // On the Race tab throughout, so the live subscription — not a reload —
    // is what has to deliver both the championship field and, later, the
    // finished-race summary.
    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    const heats = await readHeats(page, raceId);
    await recordRound(
        page,
        heats.filter((h) => h.roundId === prelim.id),
        racers,
    );
    await dismissRoundSummary(page);

    // The championship field fills in live.
    await expect(page.getByText('Placeholder 1', { exact: true })).toHaveCount(0, {
        timeout: 30000,
    });

    const finalHeats = (await readHeats(page, raceId)).filter((h) => h.roundId === final.id);
    await recordRound(page, finalHeats, racers);

    const summary = page.getByRole('dialog', { name: 'Race Complete!' });
    await expect(summary).toBeVisible({ timeout: 30000 });
    await expect(summary.getByRole('link', { name: /Final Standings/i })).toHaveAttribute(
        'href',
        `/race/${raceId}/standings`,
    );
    await expect(summary.getByRole('link', { name: /Awards/i })).toHaveAttribute(
        'href',
        `/race/${raceId}/awards`,
    );
    await expect(summary.getByRole('link', { name: /Print Results/i })).toHaveAttribute(
        'href',
        `/race/${raceId}/print/results`,
    );

    await summary.getByRole('button', { name: '×' }).click();
    await expect(summary).toBeHidden();

    // A race that finished before the screen opened is history, not news.
    await page.reload();
    await expect(page.getByRole('dialog', { name: 'Race Complete!' })).toHaveCount(0);
});

test('finishing a round built via Add Round, with no championship yet, offers to add one rather than claiming the race is over (#874)', async ({
    page,
}) => {
    // The reported bug: the summary modal said "Race Complete!" — "Every
    // heat has been run. Here's where to go next: See Final Standings" — the
    // moment a race's sole preliminary round finished, when the operator had
    // not yet had a chance to add a championship round from **Add Round**
    // (as opposed to the wizard, which pre-creates one up front, which is
    // why `createSchedule`'s wizard-built races above never tripped this).
    //
    // The tempting fix — only claim completion once a championship round
    // exists — was tried and reverted: a race that really is prelims-only
    // (raced via the wizard with no championship configured, exactly
    // `createSchedule(page, raceId)` with no second argument, as the
    // adjacent #856 test does) produces the identical shape and must still
    // raise the summary. There is no stored fact distinguishing "done" from
    // "not done building the schedule yet," so the fix is honesty rather
    // than suppression: the modal still appears, but says "No More Heats
    // Scheduled" and offers a way to add the round it might be missing,
    // alongside — never instead of — the standings link that always applies.
    //
    // `createRound` here is exactly the shape "Add Round" sends for a plain
    // general round: no `advancementSource`, unlike `createSchedule`'s
    // wizard call which can pre-create a championship round too.
    const { raceId, racers, laneCount } = await seedRace(page, 'Race Day One Round At A Time');

    await gql(
        page,
        `mutation AddGeneralRound($raceId: Int!, $roundData: RoundCreateInput!) {
            createRound(raceId: $raceId, roundData: $roundData) { id }
        }`,
        {
            raceId,
            roundData: { schedulingStrategy: 'PPC', name: 'Round 1', generalType: 'ALL', runsPerLane: 1 },
        },
    );

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    const heats = await readHeats(page, raceId);
    await recordRound(page, heats, racers);

    // Not "Race Complete!" — this schedule has no round that could only be a
    // genuine ending yet.
    const notDone = page.getByRole('dialog', { name: 'No More Heats Scheduled' });
    await expect(notDone).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('dialog', { name: 'Race Complete!' })).toHaveCount(0);
    await expect(notDone.getByRole('link', { name: 'Add a Championship Round' })).toHaveAttribute(
        'href',
        `/race/${raceId}/control`,
    );
    // The standings link is still offered — a prelims-only race really is
    // done here, and this modal cannot tell the two apart.
    await expect(notDone.getByRole('link', { name: /Final Standings/i })).toHaveAttribute(
        'href',
        `/race/${raceId}/standings`,
    );
    await notDone.getByRole('button', { name: '×' }).click();
    await expect(notDone).toBeHidden();

    // The operator now adds the championship round the modal offered.
    // Once *that* is fully raced too, the real "Race Complete!" must show.
    const rounds = await readRounds(page, raceId);
    const prelim = rounds.find((r) => r.advancementSource === null)!;
    await gql(
        page,
        `mutation AddFinal($raceId: Int!, $roundData: RoundCreateInput!) {
            createRound(raceId: $raceId, roundData: $roundData) { id }
        }`,
        {
            raceId,
            roundData: {
                schedulingStrategy: 'PPC',
                name: 'Pack Final',
                advancementSource: 'ALL',
                advancementNumRacers: laneCount,
                runsPerLane: 1,
            },
        },
    );

    const final = (await readRounds(page, raceId)).find((r) => r.id !== prelim.id)!;
    const finalHeats = (await readHeats(page, raceId))
        .filter((h) => h.roundId === final.id)
        .sort((a, b) => a.heatNumber - b.heatNumber);

    // All but the last final heat go straight to the backend, the same
    // shape the #856 test above uses. Two reasons, not one:
    //
    // `race_state:{raceId}`'s subscription used to be able to lose a
    // `HEAT_RESULT` event outright under a fast enough burst — its bounded
    // queue's drop-oldest policy assumes every payload is a superseded-by-
    // the-next snapshot, which is false for a delta naming one heat's own
    // result (#896, fixed in `backend/api/pubsub.py` — that channel no
    // longer drops). Reloading before the last heat, and running that one
    // heat live through the fake timer, is a second, independent line of
    // defence that does not depend on that fix staying in place: a reload
    // re-reads the true state fresh over plain HTTP regardless of what the
    // subscription queue did, and `TimerManager`'s own result path
    // publishes with no specific `kind`, which the client always treats as
    // needing a refetch (`raceCompletion.ts`'s docstring covers the same
    // "no event, so recovered by comparing snapshots" territory this event
    // stream sits on top of).
    //
    // It also drives the completion this test is actually about the way an
    // operator would: live, on the Race screen, rather than by writing the
    // race's last own result from outside the browser entirely and hoping
    // the summary catches up (#916 — see `raceCompletion.ts`'s
    // `heatSetKey` and `raceFlow.ts`'s `raceSummaryKey` for the client-side
    // half of that fix, which this test also exercises: the "Round
    // Complete!" summary for the championship field filling in fires
    // first, and "Race Complete!" has to override it rather than being
    // masked by it).
    await recordRound(page, finalHeats.slice(0, -1), racers);
    await page.reload();
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    const summary = page.getByRole('dialog', { name: 'Race Complete!' });
    await expect(summary).toBeVisible({ timeout: 30000 });
    await expect(summary.getByRole('link', { name: 'Add a Championship Round' })).toHaveCount(0);
});

test('a round summary can be raised again once its round is decided a second time (#856)', async ({
    page,
}) => {
    // `RaceControl`'s `roundSummary` sticky state used to clear only at its
    // own two explicit call sites — re-running the *active* heat (which
    // clears the result through `handleRunHeat`), and dismissing the summary
    // (which clears it through `handleNextHeat`). Dismissing the summary by
    // its own "×" goes through neither: it calls `flow.dismissSummary`
    // directly, hiding the modal without touching `roundSummary` at all.
    //
    // Correcting a result through Edit/Override (`handleUpdateResult`) is a
    // third path, and it never clears `roundSummary` either. That would be
    // invisible on its own — the modal is already hidden — except that
    // `raceFlow.ts`'s own "already summarised this round" guard
    // (`haveSummarised`/`summarisedRoundId`) only resets when `roundSummary`
    // itself genuinely becomes falsy. If it never does, a round that
    // un-decides and is later decided again is never re-announced: the
    // stale `roundSummary` keeps naming the same round id, so the guard
    // reads the second decision as one it has already shown.
    //
    // All but the last prelim heat are written straight to the backend —
    // fast, and it does not matter how the client learns about them, because
    // `updateHeatResult`'s own publish carries only the one heat it touched
    // (#12's cache-merge optimization) and never forces a refetch. Only the
    // *last* heat is run on screen, through the fake timer, because the
    // timer's own result path publishes with no specific `kind` and so
    // always forces a live refetch — the one thing that actually refreshes a
    // *round's* advancement status on this client, as opposed to one heat's
    // own lanes.
    const { raceId, racers } = await seedRace(page, 'Race Day Summary Reraise');
    await createSchedule(page, raceId, { name: 'Pack Final', numTopRacers: 3 });

    const rounds = await readRounds(page, raceId);
    const prelim = rounds.find((r) => r.advancementSource === null)!;
    const prelimHeats = (await readHeats(page, raceId))
        .filter((h) => h.roundId === prelim.id)
        .sort((a, b) => a.heatNumber - b.heatNumber);

    await recordRound(page, prelimHeats.slice(0, -1), racers);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();
    // The heat's own "Edit" button only appears once it holds a result — a
    // signal scoped to *this* heat, unlike counting rendered times, which
    // also matches every already-recorded heat listed under "Previous Heats".
    await expect(page.getByRole('button', { name: /^Edit(?! race)/ })).toBeVisible({
        timeout: 30000,
    });

    // The championship field just filled in live — the modal celebrating it
    // being decided.
    const summary = page.getByRole('dialog', { name: 'Round Complete!' });
    await expect(summary).toBeVisible({ timeout: 30000 });

    // Dismissed the ordinary way — an operator moving on to the next heat.
    // The modal's own "×" is `flow.dismissSummary`, not `handleNextHeat`, so
    // this does not touch `roundSummary` either way; it only hides the modal.
    await summary.getByRole('button', { name: '×' }).click();
    await expect(summary).toBeHidden();

    // Clear this heat's result through Edit — blanking every time field
    // sends exactly what `cleared()` sends for a Re-Run, so the backend
    // treats it identically, but this reaches it through the one path
    // (`handleUpdateResult`) that has no explicit clear site. The
    // preliminary round is no longer fully raced, so the championship
    // round's field reverts to placeholders.
    await page.getByRole('button', { name: /^Edit(?! race)/ }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();
    for (const input of await editor.locator('input[type="number"]').all()) {
        await input.fill('');
    }
    await editor.getByRole('button', { name: 'Save Results' }).click();
    await expect(editor).toBeHidden();

    // Run the same heat again — an ordinary "this one still needs a time"
    // action. The championship round becomes decided a second time.
    await expect(page.getByRole('button', { name: 'Start Timer' })).toBeVisible({
        timeout: 30000,
    });
    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    // A round decided a second time deserves a summary a second time.
    await expect(summary).toBeVisible({ timeout: 30000 });
});

test('clearing a result un-completes a race whose summary was already shown (#856)', async ({
    page,
}) => {
    // `raceJustCompleted` had no clear path at all — once the race finished
    // once, the flag stayed true for the rest of the page's life (see the
    // comment this replaced), so finishing the race a second time, after
    // fixing a result that turned out to be wrong, could never raise the
    // summary again.
    //
    // This race has no championship round (`createSchedule` with no second
    // argument), so the modal is titled "No More Heats Scheduled" rather
    // than "Race Complete!" (#874) — a detail this test does not otherwise
    // care about; only the sticky/un-complete mechanic below does.
    const { raceId, racers } = await seedRace(page, 'Race Day Completion Reset');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    const heats = await readHeats(page, raceId);
    await recordRound(page, heats, racers);

    const summary = page.getByRole('dialog', { name: 'No More Heats Scheduled' });
    await expect(summary).toBeVisible({ timeout: 30000 });

    // Left open deliberately, and cleared from elsewhere — the same shape as
    // the round-summary case above. Clearing any one heat's result, not
    // necessarily the last one recorded, is enough to make
    // `heats.every(hasRun)` false again.
    const toClear = (await readHeats(page, raceId)).find((h) => h.id === heats[0].id)!;
    await gql(
        page,
        `mutation ClearHeat($heatId: Int!, $lanes: [HeatLaneInput!]!) {
            updateHeatResult(heatId: $heatId, lanes: $lanes) { id }
        }`,
        {
            heatId: toClear.id,
            lanes: toClear.lanes.map((l) => ({
                lane: l.lane,
                racerId: l.racerId,
                placeholderSlot: l.placeholderSlot,
                time: null,
                place: null,
                skipped: false,
            })),
        },
    );

    await expect(summary).toBeHidden({ timeout: 30000 });
});

test('an operator override replaces the recorded time', async ({ page }) => {
    // The edit path writes the heat's lanes from the screen, which is the one
    // place a stored result is changed by hand. Worth crossing end to end
    // because the write goes out as `[HeatLaneInput!]!` and comes back through
    // the normalized cache — a field dropped in either direction reads as the
    // operator's correction not having taken.
    //
    const { raceId, laneCount } = await seedRace(page, 'Race Day Override');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();
    await expect(page.getByText(/^\d+\.\d{3}s$/)).toHaveCount(laneCount, {
        timeout: 30000,
    });

    // The heat's own "Edit" button carries a keyboard-shortcut hint in its
    // accessible name ("Edit E") and Race Control's own "Edit race" button
    // (#589) shares the "Edit" prefix, so an exact match finds neither and a
    // bare substring finds both — the lookahead is what keeps this one to
    // the heat's button specifically.
    await page.getByRole('button', { name: /^Edit(?! race)/ }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();

    // A time the fake timer never produces, so it cannot be confused with the
    // run — and away from a rounding boundary (not `x.xxx5`), so what the
    // display shows at three decimals (#763) is unambiguous rather than
    // depending on round-half behaviour.
    await editor.locator('input[type="number"]').first().fill('9.8761');
    await editor.getByRole('button', { name: 'Save Results' }).click();
    await expect(editor).toBeHidden();

    await expect(page.getByText('9.876s').first()).toBeVisible({ timeout: 30000 });

    // A fresh load of the schedule is where the stored record shows.
    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('9.876s').first()).toBeVisible({ timeout: 30000 });

    const [stored] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    expect(stored.lanes.map((l) => l.time)).toContain(9.8761);
});

test('a refused Override save keeps the modal open with what was typed (#765)', async ({ page }) => {
    // The Edit/Override modal used to close on any save, successful or not,
    // discarding every value the operator had just typed. This used to
    // provoke the refusal by giving two lanes the same place under POINTS
    // scoring — but #766 closed that route client-side (`lanes.placeIssue`
    // now disables Save before the duplicate ever reaches the server; see
    // the dedicated test for that below), so it can no longer stand in for
    // a genuine *server* refusal here.
    //
    // What still reaches the server unchecked is a heat whose lanes changed
    // underneath an open edit — the modal holds no live subscription telling
    // it a racer was deleted elsewhere while it was open, so the payload it
    // sends on Save still names a racer the server no longer has, and
    // `validate_lane_replacement` refuses it. Recording a *different* heat
    // in the round first is what makes that safe to provoke here: a round
    // with nothing raced anywhere is eligible to be silently regenerated on
    // a racer's deletion (`may_rebuild`), which would rebuild heat 1 itself
    // out from under this test rather than merely vacating one of its lanes.
    const { raceId } = await seedRace(page, 'Race Day Refused Save');
    await gql(
        page,
        `mutation SetPoints($id: Int!, $race: RaceUpdateInput!) {
            updateRace(id: $id, race: $race) { id }
        }`,
        { id: raceId, race: { scoringStrategy: 'POINTS' } },
    );
    await createSchedule(page, raceId);

    const seeded = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    const [heat1, heat2] = seeded;
    const heat1Lanes = [...heat1.lanes].sort((a, b) => a.lane - b.lane);
    const doomedRacerId = heat1Lanes[0].racerId;
    if (doomedRacerId === null) {
        throw new Error("heat 1's own lane 1 has no racer to delete — check the seeded schedule");
    }

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible({ timeout: 30000 });

    // A POINTS race with a timer still shows Override, not Enter Results
    // (#490/#525) — this track has one (FAKE).
    await page.getByRole('button', { name: 'Override' }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();

    // An ordinary, valid finishing order — #766's client-side check has
    // nothing to say about this.
    const placeInputs = editor.locator('input[type="number"]');
    await placeInputs.nth(0).fill('1');
    await placeInputs.nth(2).fill('2');

    // Meanwhile, behind the open modal: record heat 2 (so the round is no
    // longer eligible for a silent regeneration), then delete the racer
    // sitting in heat 1's own lane 1. `ON DELETE SET NULL` vacates that lane
    // the moment the delete lands — the editor already read the old value
    // and has no way to know it changed.
    await gql(
        page,
        `mutation RecordOtherHeat($heatId: Int!, $lanes: [HeatLaneInput!]!) {
            updateHeatResult(heatId: $heatId, lanes: $lanes) { id }
        }`,
        {
            heatId: heat2.id,
            lanes: heat2.lanes.map((l, idx) => ({
                lane: l.lane,
                racerId: l.racerId,
                placeholderSlot: l.placeholderSlot,
                time: idx === 0 ? 5.0 : l.time,
                place: l.place,
            })),
        },
    );
    await gql(page, `mutation DeleteDoomedRacer($id: Int!) { deleteRacer(id: $id) }`, {
        id: doomedRacerId,
    });

    await editor.getByRole('button', { name: 'Save Results' }).click();

    const errorDialog = page.getByRole('dialog', { name: 'Error' });
    await expect(errorDialog).toBeVisible({ timeout: 30000 });
    await expect(errorDialog).toContainText(/not part of this heat/i);
    await errorDialog.getByRole('button', { name: 'OK' }).click();

    // The refusal must not have closed the editor or reset what was typed.
    await expect(editor).toBeVisible();
    await expect(placeInputs.nth(0)).toHaveValue('1');
    await expect(placeInputs.nth(2)).toHaveValue('2');

    // Nothing from this Save landed on heat 1 — its lane 1 lost only the
    // racer the vacate itself cleared, and no place was ever written.
    const [heat] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    expect(heat.lanes.every((l) => l.place === null)).toBe(true);
});

test('one Escape over a refused-save alert dismisses only the alert, not the editor underneath (#870)', async ({ page }) => {
    // #788's focus-trap Escape handler listened on `document` and closed
    // unconditionally, so with the Error alert (raised by the test above)
    // open over the Edit Results editor, a single Escape closed *both* at
    // once — discarding exactly the typed-but-unsaved values #807 exists to
    // protect, and reopening #765 by a second route. Same provocation as the
    // test above, but pressing Escape instead of clicking the alert's OK.
    const { raceId } = await seedRace(page, 'Race Day Escape Stacking');
    await gql(
        page,
        `mutation SetPoints($id: Int!, $race: RaceUpdateInput!) {
            updateRace(id: $id, race: $race) { id }
        }`,
        { id: raceId, race: { scoringStrategy: 'POINTS' } },
    );
    await createSchedule(page, raceId);

    const seeded = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    const [heat1, heat2] = seeded;
    const heat1Lanes = [...heat1.lanes].sort((a, b) => a.lane - b.lane);
    const doomedRacerId = heat1Lanes[0].racerId;
    if (doomedRacerId === null) {
        throw new Error("heat 1's own lane 1 has no racer to delete — check the seeded schedule");
    }

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible({ timeout: 30000 });

    await page.getByRole('button', { name: 'Override' }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();

    const placeInputs = editor.locator('input[type="number"]');
    await placeInputs.nth(0).fill('1');
    await placeInputs.nth(2).fill('2');

    // Record heat 2 so the round can no longer be silently regenerated, then
    // delete the racer sitting in heat 1's own lane 1 so the Save this
    // editor is about to send names a racer the server no longer has.
    await gql(
        page,
        `mutation RecordOtherHeat($heatId: Int!, $lanes: [HeatLaneInput!]!) {
            updateHeatResult(heatId: $heatId, lanes: $lanes) { id }
        }`,
        {
            heatId: heat2.id,
            lanes: heat2.lanes.map((l, idx) => ({
                lane: l.lane,
                racerId: l.racerId,
                placeholderSlot: l.placeholderSlot,
                time: idx === 0 ? 5.0 : l.time,
                place: l.place,
            })),
        },
    );
    await gql(page, `mutation DeleteDoomedRacer($id: Int!) { deleteRacer(id: $id) }`, {
        id: doomedRacerId,
    });

    await editor.getByRole('button', { name: 'Save Results' }).click();

    const errorDialog = page.getByRole('dialog', { name: 'Error' });
    await expect(errorDialog).toBeVisible({ timeout: 30000 });

    // One Escape: the alert (topmost — raised over the already-open editor)
    // closes. The editor underneath must still be open, with what was typed
    // still in it.
    await page.keyboard.press('Escape');
    await expect(errorDialog).not.toBeVisible();
    await expect(editor).toBeVisible();
    await expect(placeInputs.nth(0)).toHaveValue('1');
    await expect(placeInputs.nth(2)).toHaveValue('2');

    // A second Escape now reaches the editor, since it is topmost once the
    // alert is gone — confirming this isn't "Escape does nothing now", only
    // that it targets one modal at a time.
    await page.keyboard.press('Escape');
    await expect(editor).not.toBeVisible();
});

test('a duplicate place is refused before Save is even clickable (#766)', async ({ page }) => {
    // The client-side half of the story above: giving two lanes the same
    // place under POINTS scoring used to reach the server and come back as
    // the refusal the previous test provoked a different way. `lanes.placeIssue`
    // now mirrors `crud.validate_lane_replacement`'s own rule and disables
    // Save before the round trip — this is what closed that route, so it
    // gets its own regression rather than only a unit test's word for it.
    const { raceId } = await seedRace(page, 'Race Day Duplicate Place');
    await gql(
        page,
        `mutation SetPoints($id: Int!, $race: RaceUpdateInput!) {
            updateRace(id: $id, race: $race) { id }
        }`,
        { id: raceId, race: { scoringStrategy: 'POINTS' } },
    );
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible({ timeout: 30000 });

    await page.getByRole('button', { name: 'Override' }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();

    const placeInputs = editor.locator('input[type="number"]');
    await placeInputs.nth(0).fill('1');
    await placeInputs.nth(2).fill('1');

    await expect(editor.getByText('Place 1 is assigned to more than one lane.')).toBeVisible();
    await expect(editor.getByRole('button', { name: 'Save Results' })).toBeDisabled();

    // Fixing the collision clears the error and re-enables Save — the same
    // round trip the client-side check exists to avoid never happens here.
    await placeInputs.nth(2).fill('2');
    await expect(editor.getByText(/is assigned to more than one lane/)).toBeHidden();
    await expect(editor.getByRole('button', { name: 'Save Results' })).toBeEnabled();
});

test('a skipped heat is passed over rather than left to run', async ({ page }) => {
    // `is_finished` rather than `has_results` — the distinction #55 got wrong.
    // A skipped heat holds no times, so anything asking "would rebuilding lose
    // a result" says no; but the running order must still move on, because the
    // operator is not coming back to it.
    const { raceId } = await seedRace(page, 'Race Day Skip');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: 'Skip Heat' }).click();
    // The confirmation is `showConfirm`'s own dialog, not a native
    // `window.confirm` — scope to it, since its confirm button shares the
    // "Skip Heat" label with the toolbar button that opened it.
    await page
        .getByRole('dialog', { name: 'Skip Heat' })
        .getByRole('button', { name: 'Skip Heat' })
        .click();

    // The running order moved on, without the skipped heat recording anything.
    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({
        timeout: 30000,
    });

    // Wait for the *server* to hold the skip before navigating away.
    //
    // "Heat 2 is on screen" used to be a client-side consequence that could be
    // true while `updateHeatResult` was still in flight — `RaceExecution.tsx`
    // called `onNextHeat()` before awaiting the save ("Move UI forward
    // IMMEDIATELY…"), so `page.goto`'s full document load could abort a save
    // still in flight. Serially the mutation always won that race; with the
    // suite running at once it did not, and the failure landed on the
    // assertion below rather than anywhere near the navigation that caused it.
    // #765 fixed the ordering itself — the screen now waits for the save
    // before advancing — so by the time "Heat 2" is on screen this is already
    // true; the poll stays as a direct assertion on the thing that matters
    // (the server holds the skip) rather than trusting the heading alone.
    await expect
        .poll(
            async () => {
                const [first] = (await readHeats(page, raceId)).sort(
                    (a, b) => a.heatNumber - b.heatNumber,
                );
                return first.lanes.some((l) => l.skipped);
            },
            { timeout: 30000 },
        )
        .toBe(true);

    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Skipped')).toBeVisible({ timeout: 30000 });

    const [heat] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    expect(heat.lanes.some((l) => l.skipped)).toBe(true);
    expect(heat.lanes.every((l) => l.time === null)).toBe(true);
});

test('the result controls fit above the fold at 1366×768 on a 4-lane no-timer track (#940)', async ({
    page,
}) => {
    // #940: the controls the operator needs most — the ones that record a
    // result — used to sit at the bottom of a card taller than a laptop or an
    // iPad screen, below a two-line-per-lane list. This is the layout's own
    // claim — every result control fits without scrolling — checked on the
    // exact configuration the issue measured (a no-timer track, where
    // **Enter Results** is the only way a heat is ever recorded), rather than
    // trusting a screenshot to have been looked at by a person.
    //
    // `seedRace`'s worker track is shared and configured `FAKE` (#9) — reusing
    // it here would leave every later test in this worker armed against a
    // track with no timer. A dedicated track is created and torn down instead,
    // the same shape `screenshot-timers.spec.ts` uses for its own pretend
    // hardware.
    await ensureConfigured(page);
    const retry = test.info().retry;
    const suffix = retry > 0 ? ` (retry ${retry})` : '';
    const trackName = `E2E No-Timer Track ${test.info().parallelIndex}${suffix}`;

    const trackCreated = await gql<{ createTrack: { id: number } }>(
        page,
        `mutation CreateNoTimerTrack($track: TrackInput!) { createTrack(track: $track) { id } }`,
        { track: { name: trackName, laneCount: 4, timerType: 'NONE' } },
    );
    const trackId = trackCreated.createTrack.id;
    let raceId: number | undefined;

    try {
        const config = await gql<{ organizations: { id: number }[] }>(
            page,
            `query { organizations { id } }`,
        );
        const raceCreated = await gql<{ createRace: { id: number } }>(
            page,
            `mutation CreateNoTimerRace($race: RaceInput!) { createRace(race: $race) { id } }`,
            {
                race: {
                    name: `Race Day No Timer${suffix}`,
                    organizationId: config.organizations[0].id,
                    trackId,
                    carNumberingStrategy: 'MANUAL',
                    scoringStrategy: 'TIMED',
                },
            },
        );
        raceId = raceCreated.createRace.id;

        // Four racers for four lanes — the issue's own configuration.
        for (const racer of RACERS.slice(0, 4)) {
            const created = await gql<{ createRacer: { id: number } }>(
                page,
                `mutation SeedNoTimerRacer($racer: RacerInput!) { createRacer(racer: $racer) { id } }`,
                { racer: { raceId, ...racer } },
            );
            await gql(
                page,
                `mutation SeedNoTimerCheckIn($id: Int!) {
                    checkInRacer(id: $id, passedInspection: true, weight: null) { id }
                }`,
                { id: created.createRacer.id },
            );
        }

        await createSchedule(page, raceId);

        await page.setViewportSize({ width: 1366, height: 768 });
        await page.goto(`/race/${raceId}/control/race`);

        // No timer means no "Waiting for Timer…" message and no arming — the
        // main control is Enter Results, and Skip Heat sits beside it, both
        // in the heat card's header now rather than below a full lane list.
        const actionRow = page.getByTestId('race-execution-action-row');
        const enterResults = actionRow.getByRole('button', { name: 'Enter Results' });
        const skipHeat = actionRow.getByRole('button', { name: 'Skip Heat' });
        await expect(enterResults).toBeVisible({ timeout: 30000 });
        await expect(skipHeat).toBeVisible();

        const viewport = page.viewportSize();
        expect(viewport).not.toBeNull();

        for (const control of [enterResults, skipHeat]) {
            const box = await control.boundingBox();
            expect(box).not.toBeNull();
            expect(box!.y).toBeGreaterThanOrEqual(0);
            expect(box!.y + box!.height).toBeLessThanOrEqual(viewport!.height);
        }
    } finally {
        // The race first — a track cannot be deleted while a race still
        // references it — then the track this test created for itself.
        if (raceId !== undefined) {
            await gql(page, `mutation DeleteNoTimerRace($id: Int!) { deleteRace(id: $id) }`, {
                id: raceId,
            }).catch(() => undefined);
        }
        await gql(page, `mutation DeleteNoTimerTrack($id: Int!) { deleteTrack(id: $id) }`, {
            id: trackId,
        }).catch(() => undefined);
    }
});

test('reordering a heat renumbers it without moving its field', async ({ page }) => {
    // Drag and drop, driven from the keyboard: `ScheduleManagement` registers
    // dnd-kit's `KeyboardSensor` alongside the pointer one, and a synthesised
    // mouse drag against a sortable list is the flakiest thing a browser test
    // can do. Space lifts, an arrow moves, Space drops.
    //
    // The claim worth crossing the wire is the second half. `reorderHeats`
    // reassigns `heat_number`; it does not move racers between heats. A bug
    // that swapped the fields instead would leave the schedule looking exactly
    // the same and put every car in the wrong heat.
    const { raceId } = await seedRace(page, 'Race Day Reorder');
    await createSchedule(page, raceId);

    const before = await readHeats(page, raceId);
    const fieldOf = (heats: typeof before, id: number) =>
        heats.find((h) => h.id === id)!.lanes.map((l) => l.racerId);
    const [first, second] = [...before].sort((a, b) => a.heatNumber - b.heatNumber);

    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    await page.locator('[aria-roledescription="sortable"]').first().focus();
    // The pauses are the interaction, not a workaround: dnd-kit animates the
    // lift and the move, and firing all three keys in one tick drops the item
    // back where it started.
    await page.keyboard.press('Space');
    await page.waitForTimeout(300);
    await page.keyboard.press('ArrowDown');
    await page.waitForTimeout(300);
    await page.keyboard.press('Space');

    await expect
        .poll(
            async () => {
                const heats = await readHeats(page, raceId);
                return heats.find((h) => h.id === first.id)!.heatNumber;
            },
            { timeout: 30000 },
        )
        .toBe(2);

    const after = await readHeats(page, raceId);
    expect(after.find((h) => h.id === second.id)!.heatNumber).toBe(1);

    // Every heat keeps the racers it was scheduled with — only the numbers moved.
    for (const heat of before) {
        expect(fieldOf(after, heat.id)).toEqual(fieldOf(before, heat.id));
    }

    // And the rest of the round is undisturbed.
    const untouched = before.filter((h) => h.id !== first.id && h.id !== second.id);
    for (const heat of untouched) {
        expect(after.find((h) => h.id === heat.id)!.heatNumber).toBe(heat.heatNumber);
    }
});

test('with auto-advance off the screen stays on the heat that just ran', async ({ page }) => {
    // #130. The execution view falls back to "the first heat still to be run",
    // and recording a heat changes which heat that is — so the screen used to
    // slide to the next one within a render of the result arriving, taking the
    // recorded heat's controls with it.
    //
    // Only reachable with a real backend moving the data underneath:
    // `raceFlow.test.ts` dispatches events directly and `RaceExecution.test.tsx`
    // is handed a fixed heat, so neither can see the heat change beneath them.
    const { raceId } = await seedRace(page, 'Race Day Stays Put');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    // The recorded heat's own controls, all three of which were unreachable.
    // See the lookahead's own comment above: an exact match misses this
    // button too, since its accessible name includes the "E" shortcut hint.
    await expect(page.getByRole('button', { name: /^Edit(?! race)/ })).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('button', { name: /^Next Heat/ })).toBeVisible();

    // Long enough that an auto-advance would have fired: the countdown is ten
    // seconds, and the toggle is off.
    await page.waitForTimeout(13000);
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: /^Next Heat/ }).click();
    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({ timeout: 30000 });
});

test('with auto-advance on the countdown runs and then advances', async ({ page }) => {
    // The other half of #130: `raceFlow.ts`'s COUNTING_DOWN state, which was
    // unreachable in *both* toggle positions because the machine takes the
    // active heat's phase as its input and never saw RECORDED.
    const { raceId } = await seedRace(page, 'Race Day Countdown');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    // The checkbox is visually hidden behind the slider, so click what the
    // operator clicks. Named rather than "the only checkbox on the page" —
    // the finish-sound toggle (#208) is beside it now.
    const autoAdvance = page.getByTestId('auto-advance-toggle');
    await page.locator('label').filter({ has: autoAdvance }).click();
    await expect(autoAdvance).toBeChecked();

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    // Counting, on the recorded heat, with the option to call it off.
    await expect(page.getByRole('button', { name: /^Next Heat \(\d+s\)/ })).toBeVisible({
        timeout: 30000,
    });
    await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({ timeout: 30000 });
});

test('the wizard promises the heat count the backend then generates', async ({ page }) => {
    // #140. The estimate divided by the lane count, which is the arithmetic for
    // a scheduler that packs racers into heats. PPC seeds lane 1 with every
    // racer, so a round is one heat per racer however wide the track is — the
    // wizard was out by a factor of the lane count, on both the heat count and
    // the run time it derives from it.
    //
    // The two numbers live on opposite sides of the wire: a `useMemo` in
    // `RoundWizard.tsx` and `domain/scheduling.generate_ppc`. Nothing held both
    // at once, which is how they disagreed for so long — and why this test
    // reads the promise off the screen and then counts what actually arrives,
    // rather than asserting a number either side would have to be told.
    const { raceId, racers, laneCount } = await seedRace(page, 'Race Day Estimate');

    await page.goto(`/race/${raceId}/control`);
    await page.getByRole('button', { name: /Start Round Creation Wizard/i }).click();
    await expect(page.getByRole('heading', { name: 'Race Schedule Wizard' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Next' }).click();

    const promised = Number(
        (await page.getByText(/Total Heats: \d+/).innerText()).match(/\d+/)![0],
    );

    await page.getByRole('button', { name: 'Generate schedule' }).click();
    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    const heats = await readHeats(page, raceId);
    expect(promised).toBe(heats.length);

    // And the shape of it, so a coincidence cannot pass: the preliminary round
    // is one heat per racer, whatever the lane count.
    const prelim = (await readRounds(page, raceId)).find((r) => r.advancementSource === null)!;
    expect(heats.filter((h) => h.roundId === prelim.id)).toHaveLength(racers.length);
    expect(racers.length).toBeGreaterThan(laneCount);
});

test('a live screen recovers when the network drops under it', async ({ page, context, request }) => {
    // The deployment is a Pi at the front of a room and screens on venue wifi,
    // so a subscription socket dropping mid-event is ordinary rather than
    // exceptional. Every payload these subscriptions send is a full snapshot,
    // which is what makes recovery possible at all — there is no delta stream
    // to fall behind in — but only if the client reconnects.
    //
    // What this pins is that recovery happens end to end: the socket comes
    // back, resubscribes, and the snapshot lands in the normalized cache with
    // no reload. The specific retry and keep-alive policy is pinned by
    // `liveConnection.test.ts`; a short outage like this one would be survived
    // by a laxer policy too.
    const { raceId, racers } = await seedRace(page, 'Race Day Reconnect');
    await createSchedule(page, raceId);
    const heats = await readHeats(page, raceId);

    await page.goto(`/race/${raceId}/standings`);
    await expect(page.getByText('No results yet')).toBeVisible({ timeout: 30000 });

    await context.setOffline(true);

    // Recorded through Playwright's own request context, which is not tied to
    // the browser context and so is still reachable while the page is not.
    // Everything that would tell the page about this arrives over the socket
    // that is currently down.
    for (const heat of heats) {
        const lanes = heat.lanes.map((lane) => {
            const racer = racers.find((r) => r.id === lane.racerId);
            return {
                lane: lane.lane,
                racerId: lane.racerId,
                placeholderSlot: lane.placeholderSlot,
                time: racer ? 3 + racer.carNumber / 100 : null,
                place: null,
                skipped: false,
            };
        });
        const response = await request.post(`${BACKEND_URL}/graphql`, {
            data: JSON.stringify({
                query: `mutation Rec($heatId: Int!, $lanes: [HeatLaneInput!]!) {
                    updateHeatResult(heatId: $heatId, lanes: $lanes) { id }
                }`,
                variables: { heatId: heat.id, lanes },
            }),
            headers: { 'Content-Type': 'application/json' },
        });
        expect((await response.json()).errors).toBeUndefined();
    }

    // Still nothing on screen: the results exist, and the page cannot hear it.
    await expect(page.getByText('No results yet')).toBeVisible();

    await context.setOffline(false);

    // No reload anywhere in this test. If the standings appear, the socket
    // reconnected and the resubscribe snapshot reached the cache. The whole
    // roster, not one racer of six — a partial or stale snapshot could show a
    // single row and still pass.
    for (const racer of racers) {
        await expect(
            page.getByRole('row').filter({ hasText: `${racer.firstName} ${racer.lastName}` }),
        ).toBeVisible({ timeout: 60000 });
    }
});

test("Home badges a race's schedule status as heats are generated and run (#847)", async ({ page }) => {
    // The other half of #847 item 3 — #917 built the route to the results
    // but deliberately left this badge undone, because the question needs a
    // race's heats and lanes and Home's `GetRaces` query is pinned to a
    // constant SQL cost regardless of race count (#749). This is the round
    // trip: a real schedule generated by clicking through the wizard's own
    // mutation, real results recorded, and Home re-read fresh on each visit.
    const { raceId, racers } = await seedRace(page, 'Race Day Status Badge');

    await page.goto('/');
    const row = page.getByRole('row').filter({ hasText: 'Race Day Status Badge' });
    await expect(row.getByText('Not started')).toBeVisible();

    // A schedule exists now, but nothing on it has been raced or skipped —
    // still "not started", the same word as before any heats were generated
    // at all (see `domain/race_status.py`'s module docstring for why the two
    // are not split into a fourth word).
    await createSchedule(page, raceId);
    await page.goto('/');
    await expect(row.getByText('Not started')).toBeVisible();

    const heats = await readHeats(page, raceId);
    expect(heats.length).toBeGreaterThan(1);
    await recordRound(page, [heats[0]], racers);

    await page.goto('/');
    await expect(row.getByText('In progress')).toBeVisible();

    await recordRound(page, heats, racers);
    await page.goto('/');
    await expect(row.getByText('Finished')).toBeVisible();
});

test('confirming Delete round actually removes it (#939)', async ({ page }) => {
    // `handleDeleteHeat` already went through `showConfirm`; `handleDeleteRound`
    // did not, and used to call the mutation the moment the button was
    // clicked. Cancelling-does-not-mutate is covered by
    // `RaceControlScheduleConfirm.test.tsx` with a mocked mutation — what
    // that test can't prove is that confirming actually reaches the
    // GraphQL round trip and the round is genuinely gone afterwards.
    const { raceId } = await seedRace(page, 'Race Day Delete Round Confirm');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible();

    await page.getByRole('button', { name: 'Delete All Pack' }).click();

    const confirmDialog = page.getByRole('dialog', { name: 'Delete Round' });
    await expect(confirmDialog).toBeVisible();
    await expect(confirmDialog.getByText(/heats have not been run\. This cannot be undone\./)).toBeVisible();
    await confirmDialog.getByRole('button', { name: 'Delete' }).click();

    await expect(confirmDialog).toBeHidden();
    await expect(page.getByText('Heat 1', { exact: true })).toHaveCount(0);
    expect(await readRounds(page, raceId)).toHaveLength(0);
});
