/**
 * Race day, end to end: a real backend, a real browser, a real timer path.
 *
 * The rules these tests cross are each well covered by a unit test — the PPC
 * scheduler in `test_domain_scheduling.py`, scoring in `domain/scoring.py`,
 * advancement in `domain/advancement.py`. What is not covered anywhere else is
 * that those answers still arrive intact after a GraphQL round trip and a pass
 * through the normalized cache, which is precisely where a #12-era bug lives:
 * the payload is well formed, the rule is right, and the screen shows nothing.
 *
 * Deliberately one test per question, each seeding its own race. The docs
 * screenshot specs are a single long `test()` where every step depends on the
 * last, and a break a third of the way through looked for months like a spec
 * that ran (#114). Splitting costs a few seconds of setup and buys a failure
 * that names itself.
 *
 * Run with:
 *   cd frontend && npm run test:e2e
 */

import { test, expect } from '@playwright/test';
import {
    BACKEND_URL,
    createSchedule,
    dismissRoundSummary,
    readHeats,
    readRounds,
    recordRound,
    seedRace,
} from './support';

test('the wizard generates a schedule that fills every lane', async ({ page }) => {
    // #26: greedy lane filling finds a maximal matching, not a maximum one, and
    // used to strand a lane in roughly one in four four-lane schedules — which
    // under POINTS scoring made the short-changed racer's score *better*. The
    // property is held by `test_domain_scheduling.py`; this is the same claim
    // made about a schedule the operator actually generated by clicking.
    const { raceId, laneCount, racers } = await seedRace(page, 'Race Day Schedule');

    await page.goto(`/race/${raceId}/control`);
    await page.getByRole('button', { name: /Start Round Creation Wizard/i }).click();
    await expect(page.getByRole('heading', { name: 'Race Schedule Wizard' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Generate Schedule' }).click();

    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    // The wizard's own defaults add a championship round, whose lanes are
    // undecided slots rather than racers. This claim is about the preliminary
    // round, where the field is the roster.
    const prelim = (await readRounds(page, raceId)).find((r) => r.advancementSource === null)!;
    const heats = (await readHeats(page, raceId)).filter((h) => h.roundId === prelim.id);

    // Lane 1 is seeded with every racer, which fixes the heat count.
    expect(heats).toHaveLength(racers.length);
    for (const heat of heats) {
        expect(heat.lanes.filter((l) => l.racerId !== null)).toHaveLength(laneCount);
    }

    // Every racer therefore runs once per lane, and nobody runs a heat fewer.
    const appearances = new Map(racers.map((r) => [r.id, 0]));
    for (const heat of heats) {
        for (const lane of heat.lanes) {
            if (lane.racerId !== null) {
                appearances.set(lane.racerId, appearances.get(lane.racerId)! + 1);
            }
        }
    }
    expect([...appearances.values()]).toEqual(racers.map(() => laneCount));
});

test('a heat run on the timer records times that survive a reload', async ({ page }) => {
    // The whole timer path: arming over a subscription, the fake device driving
    // `TimerManager` through the same code a serial one does, the result
    // reaching the database, and the screen showing the stored record rather
    // than the pending times it was showing a moment earlier (#7).
    const { raceId, laneCount } = await seedRace(page, 'Race Day Timer');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    // No lane has a time before the heat is run — otherwise the assertion below
    // would pass against a heat that was already recorded.
    const times = page.getByText(/^\d+\.\d{4}s$/);
    await expect(times).toHaveCount(0);

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    await expect(times).toHaveCount(laneCount, { timeout: 30000 });

    // A time on screen is not yet a stored result: until `record_heat_result`
    // runs it is the manager's pending state, and an abort still loses it. The
    // schedule is where a fresh page load shows the record — the execution view
    // moves on to the first heat still to be run, which is the next one.
    await page.goto(`/race/${raceId}/control`);
    await expect(times).toHaveCount(laneCount, { timeout: 30000 });

    const [heat] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    const run = heat.lanes.filter((l) => l.racerId !== null);
    expect(run.map((l) => l.time).every((t) => t !== null)).toBe(true);
    expect([...run].map((l) => l.place).sort((a, b) => a! - b!)).toEqual(
        Array.from({ length: laneCount }, (_, i) => i + 1),
    );
});

test('standings arrive over the subscription without a reload', async ({ page }) => {
    // The leaderboard is subscription-fed, so this is the one path where a
    // typed payload landing in the normalized cache is the whole feature (#12).
    // A query-backed version of this test would pass with the subscription
    // broken.
    const { raceId, racers } = await seedRace(page, 'Race Day Standings');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/standings`);
    await expect(page.getByText('No results yet')).toBeVisible({ timeout: 30000 });

    const heats = await readHeats(page, raceId);
    await recordRound(page, heats, racers);

    // No reload: if the row appears, the subscription delivered it.
    const rows = page.getByRole('row');
    await expect(rows.filter({ hasText: 'Ada Ant' })).toBeVisible({ timeout: 30000 });

    // Car number decides the times `recordRound` writes, so the standings are
    // the roster in car-number order.
    const names = await page.getByRole('row').allInnerTexts();
    const ranked = names
        .slice(1)
        .map((row) => row.split('\t').find((cell) => /\w+ \w+/.test(cell)));
    expect(ranked.slice(0, 3)).toEqual(['Ada Ant', 'Ben Bear', 'Cy Cat']);

    // Everyone ran every heat of the round, so nobody is short.
    for (const row of await rows.all()) {
        const text = await row.innerText();
        if (text.includes('Rank')) continue;
        expect(text).not.toContain('\t-\t');
    }
});

test('finishing the prelims fills the championship round with the top finishers', async ({
    page,
}) => {
    // `record_heat_result` re-runs advancement on every result, so a final's
    // field is decided by the cascade rather than by an operator action. Until
    // it fires the round holds placeholders and `phase` reports NOT_READY,
    // which leaves the operator screen with no controls at all.
    const { raceId, racers } = await seedRace(page, 'Race Day Championship');
    await createSchedule(page, raceId, { name: 'Pack Final', numTopRacers: 3 });

    const rounds = await readRounds(page, raceId);
    const prelim = rounds.find((r) => r.advancementSource === null)!;
    const final = rounds.find((r) => r.advancementSource !== null)!;

    // Before any result, the final's lanes are undecided slots.
    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Placeholder 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    const heats = await readHeats(page, raceId);
    await recordRound(
        page,
        heats.filter((h) => h.roundId === prelim.id),
        racers,
    );

    await page.reload();
    await dismissRoundSummary(page);

    for (const name of ['Ada Ant', 'Ben Bear', 'Cy Cat']) {
        await expect(page.getByText(`${name} (#`, { exact: false }).first()).toBeVisible({
            timeout: 30000,
        });
    }
    await expect(page.getByText('Placeholder 1', { exact: true })).toHaveCount(0);

    const finalHeats = (await readHeats(page, raceId)).filter((h) => h.roundId === final.id);
    const fielded = new Set(
        finalHeats.flatMap((h) => h.lanes.map((l) => l.racerId).filter((id) => id !== null)),
    );
    expect([...fielded].sort((a, b) => a! - b!)).toEqual(
        racers
            .filter((r) => r.carNumber <= 3)
            .map((r) => r.id)
            .sort((a, b) => a - b),
    );
});

test('an operator override replaces the recorded time', async ({ page }) => {
    // The edit path writes the heat's lanes from the screen, which is the one
    // place a stored result is changed by hand. Worth crossing end to end
    // because the write goes out as `[HeatLaneInput!]!` and comes back through
    // the normalized cache — a field dropped in either direction reads as the
    // operator's correction not having taken.
    //
    const { raceId, laneCount } = await seedRace(page, 'Race Day Override');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();
    await expect(page.getByText(/^\d+\.\d{4}s$/)).toHaveCount(laneCount, {
        timeout: 30000,
    });

    await page.getByRole('button', { name: 'Edit' }).click();
    const editor = page.getByRole('dialog', { name: /Edit Results/ });
    await expect(editor).toBeVisible();

    // A time the fake timer never produces, so it cannot be confused with the run.
    await editor.locator('input[type="number"]').first().fill('9.8765');
    await editor.getByRole('button', { name: 'Save Results' }).click();
    await expect(editor).toBeHidden();

    await expect(page.getByText('9.8765s').first()).toBeVisible({ timeout: 30000 });

    // A fresh load of the schedule is where the stored record shows.
    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('9.8765s').first()).toBeVisible({ timeout: 30000 });

    const [stored] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    expect(stored.lanes.map((l) => l.time)).toContain(9.8765);
});

test('a skipped heat is passed over rather than left to run', async ({ page }) => {
    // `is_finished` rather than `has_results` — the distinction #55 got wrong.
    // A skipped heat holds no times, so anything asking "would rebuilding lose
    // a result" says no; but the running order must still move on, because the
    // operator is not coming back to it.
    const { raceId } = await seedRace(page, 'Race Day Skip');
    await createSchedule(page, raceId);

    page.on('dialog', (dialog) => dialog.accept());

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: 'Skip Heat' }).click();

    // The running order moved on, without the skipped heat recording anything.
    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({
        timeout: 30000,
    });

    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Skipped')).toBeVisible({ timeout: 30000 });

    const [heat] = (await readHeats(page, raceId)).sort((a, b) => a.heatNumber - b.heatNumber);
    expect(heat.lanes.some((l) => l.skipped)).toBe(true);
    expect(heat.lanes.every((l) => l.time === null)).toBe(true);
});

test('reordering a heat renumbers it without moving its field', async ({ page }) => {
    // Drag and drop, driven from the keyboard: `ScheduleManagement` registers
    // dnd-kit's `KeyboardSensor` alongside the pointer one, and a synthesised
    // mouse drag against a sortable list is the flakiest thing a browser test
    // can do. Space lifts, an arrow moves, Space drops.
    //
    // The claim worth crossing the wire is the second half. `reorderHeats`
    // reassigns `heat_number`; it does not move racers between heats. A bug
    // that swapped the fields instead would leave the schedule looking exactly
    // the same and put every car in the wrong heat.
    const { raceId } = await seedRace(page, 'Race Day Reorder');
    await createSchedule(page, raceId);

    const before = await readHeats(page, raceId);
    const fieldOf = (heats: typeof before, id: number) =>
        heats.find((h) => h.id === id)!.lanes.map((l) => l.racerId);
    const [first, second] = [...before].sort((a, b) => a.heatNumber - b.heatNumber);

    await page.goto(`/race/${raceId}/control`);
    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    await page.locator('[aria-roledescription="sortable"]').first().focus();
    // The pauses are the interaction, not a workaround: dnd-kit animates the
    // lift and the move, and firing all three keys in one tick drops the item
    // back where it started.
    await page.keyboard.press('Space');
    await page.waitForTimeout(300);
    await page.keyboard.press('ArrowDown');
    await page.waitForTimeout(300);
    await page.keyboard.press('Space');

    await expect
        .poll(
            async () => {
                const heats = await readHeats(page, raceId);
                return heats.find((h) => h.id === first.id)!.heatNumber;
            },
            { timeout: 30000 },
        )
        .toBe(2);

    const after = await readHeats(page, raceId);
    expect(after.find((h) => h.id === second.id)!.heatNumber).toBe(1);

    // Every heat keeps the racers it was scheduled with — only the numbers moved.
    for (const heat of before) {
        expect(fieldOf(after, heat.id)).toEqual(fieldOf(before, heat.id));
    }

    // And the rest of the round is undisturbed.
    const untouched = before.filter((h) => h.id !== first.id && h.id !== second.id);
    for (const heat of untouched) {
        expect(after.find((h) => h.id === heat.id)!.heatNumber).toBe(heat.heatNumber);
    }
});

test('with auto-advance off the screen stays on the heat that just ran', async ({ page }) => {
    // #130. The execution view falls back to "the first heat still to be run",
    // and recording a heat changes which heat that is — so the screen used to
    // slide to the next one within a render of the result arriving, taking the
    // recorded heat's controls with it.
    //
    // Only reachable with a real backend moving the data underneath:
    // `raceFlow.test.ts` dispatches events directly and `RaceExecution.test.tsx`
    // is handed a fixed heat, so neither can see the heat change beneath them.
    const { raceId } = await seedRace(page, 'Race Day Stays Put');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    // The recorded heat's own controls, all three of which were unreachable.
    await expect(page.getByRole('button', { name: 'Edit' })).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('button', { name: /^Next Heat/ })).toBeVisible();

    // Long enough that an auto-advance would have fired: the countdown is ten
    // seconds, and the toggle is off.
    await page.waitForTimeout(13000);
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await page.getByRole('button', { name: /^Next Heat/ }).click();
    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({ timeout: 30000 });
});

test('with auto-advance on the countdown runs and then advances', async ({ page }) => {
    // The other half of #130: `raceFlow.ts`'s COUNTING_DOWN state, which was
    // unreachable in *both* toggle positions because the machine takes the
    // active heat's phase as its input and never saw RECORDED.
    const { raceId } = await seedRace(page, 'Race Day Countdown');
    await createSchedule(page, raceId);

    await page.goto(`/race/${raceId}/control/race`);
    await expect(page.getByText('Ready to start')).toBeVisible({ timeout: 30000 });

    // The checkbox is visually hidden behind the slider, so click what the
    // operator clicks. Named rather than "the only checkbox on the page" —
    // the finish-sound toggle (#208) is beside it now.
    const autoAdvance = page.getByTestId('auto-advance-toggle');
    await page.locator('label').filter({ has: autoAdvance }).click();
    await expect(autoAdvance).toBeChecked();

    await page.getByRole('button', { name: 'Start Timer' }).click();
    await page.getByRole('button', { name: 'Finish Heat' }).click();

    // Counting, on the recorded heat, with the option to call it off.
    await expect(page.getByRole('button', { name: /^Next Heat \(\d+s\)/ })).toBeVisible({
        timeout: 30000,
    });
    await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Heat 1' })).toBeVisible();

    await expect(page.getByRole('heading', { name: 'Heat 2' })).toBeVisible({ timeout: 30000 });
});

test('the wizard promises the heat count the backend then generates', async ({ page }) => {
    // #140. The estimate divided by the lane count, which is the arithmetic for
    // a scheduler that packs racers into heats. PPC seeds lane 1 with every
    // racer, so a round is one heat per racer however wide the track is — the
    // wizard was out by a factor of the lane count, on both the heat count and
    // the run time it derives from it.
    //
    // The two numbers live on opposite sides of the wire: a `useMemo` in
    // `RoundWizard.tsx` and `domain/scheduling.generate_ppc`. Nothing held both
    // at once, which is how they disagreed for so long — and why this test
    // reads the promise off the screen and then counts what actually arrives,
    // rather than asserting a number either side would have to be told.
    const { raceId, racers, laneCount } = await seedRace(page, 'Race Day Estimate');

    await page.goto(`/race/${raceId}/control`);
    await page.getByRole('button', { name: /Start Round Creation Wizard/i }).click();
    await expect(page.getByRole('heading', { name: 'Race Schedule Wizard' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Next' }).click();

    const promised = Number(
        (await page.getByText(/Total Heats: \d+/).innerText()).match(/\d+/)![0],
    );

    await page.getByRole('button', { name: 'Generate Schedule' }).click();
    await expect(page.getByText('Heat 1', { exact: true }).first()).toBeVisible({
        timeout: 30000,
    });

    const heats = await readHeats(page, raceId);
    expect(promised).toBe(heats.length);

    // And the shape of it, so a coincidence cannot pass: the preliminary round
    // is one heat per racer, whatever the lane count.
    const prelim = (await readRounds(page, raceId)).find((r) => r.advancementSource === null)!;
    expect(heats.filter((h) => h.roundId === prelim.id)).toHaveLength(racers.length);
    expect(racers.length).toBeGreaterThan(laneCount);
});

test('a live screen recovers when the network drops under it', async ({ page, context, request }) => {
    // The deployment is a Pi at the front of a room and screens on venue wifi,
    // so a subscription socket dropping mid-event is ordinary rather than
    // exceptional. Every payload these subscriptions send is a full snapshot,
    // which is what makes recovery possible at all — there is no delta stream
    // to fall behind in — but only if the client reconnects.
    //
    // What this pins is that recovery happens end to end: the socket comes
    // back, resubscribes, and the snapshot lands in the normalized cache with
    // no reload. The specific retry and keep-alive policy is pinned by
    // `liveConnection.test.ts`; a short outage like this one would be survived
    // by a laxer policy too.
    const { raceId, racers } = await seedRace(page, 'Race Day Reconnect');
    await createSchedule(page, raceId);
    const heats = await readHeats(page, raceId);

    await page.goto(`/race/${raceId}/standings`);
    await expect(page.getByText('No results yet')).toBeVisible({ timeout: 30000 });

    await context.setOffline(true);

    // Recorded through Playwright's own request context, which is not tied to
    // the browser context and so is still reachable while the page is not.
    // Everything that would tell the page about this arrives over the socket
    // that is currently down.
    for (const heat of heats) {
        const lanes = heat.lanes.map((lane) => {
            const racer = racers.find((r) => r.id === lane.racerId);
            return {
                lane: lane.lane,
                racerId: lane.racerId,
                placeholderSlot: lane.placeholderSlot,
                time: racer ? 3 + racer.carNumber / 100 : null,
                place: null,
                skipped: false,
            };
        });
        const response = await request.post(`${BACKEND_URL}/graphql`, {
            data: JSON.stringify({
                query: `mutation Rec($heatId: Int!, $lanes: [HeatLaneInput!]!) {
                    updateHeatResult(heatId: $heatId, lanes: $lanes) { id }
                }`,
                variables: { heatId: heat.id, lanes },
            }),
            headers: { 'Content-Type': 'application/json' },
        });
        expect((await response.json()).errors).toBeUndefined();
    }

    // Still nothing on screen: the results exist, and the page cannot hear it.
    await expect(page.getByText('No results yet')).toBeVisible();

    await context.setOffline(false);

    // No reload anywhere in this test. If the standings appear, the socket
    // reconnected and the resubscribe snapshot reached the cache.
    await expect(page.getByRole('row').filter({ hasText: 'Ada Ant' })).toBeVisible({
        timeout: 60000,
    });
});
