/**
 * The seven themes (#498), as plain data.
 *
 * A theme has no behavior — it is a set of CSS custom property values a
 * small number of DOM nodes already know how to consume (see
 * `applyTheme.ts`). A subclass or a per-theme stylesheet would mean seven
 * copies of selectors that have to be kept in sync with every future
 * component that adds a new colored element; a plain record means adding a
 * theme is adding one object to `THEMES`, and a missing token falls back to
 * whatever the browser resolves — nothing breaks, it just under-themes.
 *
 * This file is the *one* place these values live. Nothing else — not a CSS
 * file, not the backend — holds a second copy of what a theme's colors are;
 * `index.css`'s `:root` block keeps only Field Uniform's own values, as the
 * pre-JS/no-script fallback, and they are required to match this file's
 * `field-uniform` record exactly (`themes.test.ts` pins that).
 *
 * Where every value below comes from: the seven token tables in
 * https://github.com/dknowles2/trusty-track/issues/498, transcribed exactly
 * — including the accessibility notes reproduced as comments next to the
 * pairing they measure, so a future edit to a color has to also edit (or at
 * least notice) the ratio it was chosen to clear.
 */

/** Every theme this build ships, by key. Never renamed once shipped — it is
 *  API, stored on `Organization.display_theme` / `Organization.printables_theme` and in
 *  each device's `localStorage`. */
export type ThemeKey =
  | 'field-uniform'
  | 'under-the-lights'
  | 'old-glory'
  | 'clear-sight'
  | 'sawdust-and-pine'
  | 'trail-colors'
  | 'newsprint';

/**
 * What Display and Printables are actually set to.
 *
 * `'MATCH_APP'` is the stored sentinel behind the pickers' default option —
 * labelled "Field Uniform (default)" in `ThemePicker.tsx`, not "Match App
 * theme": the App theme is per-device `localStorage` and never reaches the
 * server, so nothing outside one device could ever resolve it against "the
 * App picker's current value" (#528). It always resolves to Field Uniform's
 * own Display (or Printables) definition. See `resolveSurfaceKey` in
 * `applyTheme.ts`.
 */
export type SurfaceThemeSetting = 'MATCH_APP' | ThemeKey;

/** Which of the three surfaces — used by the settings picker/preview to pick
 *  the right pair of tokens off a `Theme` without repeating the surface
 *  names as string literals at every call site. */
export type PickerSurface = 'app' | 'display' | 'printables';

/** One surface's token values, plus whether it reads dark or light —
 *  `AwardArtwork`'s `variant`, the focus-ring choice on a dark surface, and
 *  a preview panel's own iconography all key off this rather than eyeballing
 *  a background color. */
export interface SurfaceTheme {
  /** CSS custom property name (e.g. `--scouting-blue`) -> value. */
  tokens: Readonly<Record<string, string>>;
  isDark: boolean;
}

/** Whether a Printables theme's palette survives being printed as specified,
 *  is deliberately lightened for the page even though the App/Display
 *  surfaces went dark, or (no theme here does this) would be refused. */
export type PrintBehavior = 'as-is' | 'lightened' | 'refused';

export interface PrintablesSurfaceTheme extends SurfaceTheme {
  printBehavior: PrintBehavior;
  printNote?: string;
}

export interface Theme {
  key: ThemeKey;
  /** What the picker calls it. */
  name: string;
  /** One sentence, parent-volunteer voice. */
  description: string;
  /** When a pack would choose it — the picker's second line. */
  occasion: string;
  app: SurfaceTheme;
  display: SurfaceTheme;
  printables: PrintablesSurfaceTheme;
}

/**
 * Every App-surface token name a theme may set. `applyTheme` clears any name
 * in this list that a theme's `tokens` map omits, so switching themes can
 * never leave a stale inline override from the theme before it — the
 * mechanism `--print-decor-color` and the Newsprint header specifically
 * depend on (see `PRINTABLES_TOKEN_NAMES` below).
 */
export const APP_TOKEN_NAMES: readonly string[] = [
  '--background-color',
  '--surface-color',
  '--surface-alt-color',
  '--text-color',
  '--text-muted-color',
  '--border-color',
  '--scouting-blue',
  '--cub-scouting-gold',
  '--scouting-red',
  '--on-primary-color',
  '--on-accent-color',
  '--focus-ring-color',
  // Added by #501's app-surface sweep — every one of these gives a name to a
  // literal that recurred across many files with the *same* exact value, so
  // converting kept the rendered color under Field Uniform identical while
  // making the color respond to a theme change. Each is grouped by the role
  // it plays, not by which file it came from.
  '--divider-color',
  '--input-border-color',
  '--text-subtle-color',
  '--text-faint-color',
  '--text-placeholder-color',
  '--text-quiet-color',
  '--text-faintest-color',
  '--text-strong-color',
  '--text-heading-alt-color',
  '--text-strong-muted-color',
  '--text-emphasis-color',
  '--surface-tint-color',
  '--surface-hover-color',
  '--surface-soft-color',
  '--surface-faint-color',
  '--surface-strong-color',
  '--border-faint-color',
  '--success-color',
  '--success-bg-color',
  '--success-accent-color',
  '--warning-color',
  '--warning-bg-color',
  '--warning-strong-color',
  '--warning-strong-bg-color',
  '--warning-strong-border-color',
  '--danger-strong-color',
  '--danger-bg-color',
  '--danger-border-color',
  '--danger-accent-color',
  '--info-accent-color',
  '--active-accent-color',
  '--overlay-backdrop-color',
  '--overlay-backdrop-soft-color',
  '--overlay-backdrop-strong-color',
  '--overlay-backdrop-demo-color',
  '--link-color',
  '--banner-active-bg-color',
  '--banner-success-bg-color',
  '--banner-success-color',
  // Round 2 — residual literals found sweeping the remaining ~140 files.
  // Kept at the same value across all seven themes (unlike the first batch,
  // these are secondary/status accents rather than surface roles, and only
  // Field Uniform's value is contract-pinned).
  '--scouting-blue-hover-color',
  '--table-row-hover-color',
  '--highlight-card-bg-color',
  '--record-highlight-bg-color',
  '--neutral-accent-color',
  '--running-accent-color',
  '--hardware-connect-color',
  '--hardware-connect-hover-color',
  '--danger-accent-bg-color',
  '--caution-bg-color',
  '--caution-text-color',
  '--caution-border-color',
  '--caution-icon-color',
  '--warning-alt-border-color',
  '--info-panel-bg-color',
  '--info-panel-border-color',
  '--info-notice-bg-color',
  '--warning-notice-border-color',
  '--warning-notice-text-color',
  '--highlight-gold-tint-color',
  '--selection-accent-color',
  '--accent-blue-color',
  '--accent-blue-bg-color',
  '--accent-blue-strong-color',
  '--accent-blue-emphasis-color',
  '--wizard-heading-color',
  '--wizard-text-color',
  '--wizard-text-muted-color',
  '--wizard-text-subtle-color',
  '--wizard-border-color',
  '--wizard-border-muted-color',
  '--wizard-icon-muted-color',
  '--wizard-surface-alt-color',
  '--wizard-chip-bg-color',
  '--surface-removed-color',
  '--danger-soft-bg-color',
  '--preview-border-color',
  '--progress-track-color',
  '--attention-accent-color',
  '--neutral-info-color',
  '--info-highlight-bg-color',
  '--info-highlight-border-color',
  '--warning-alt-color',
  '--danger-faint-bg-color',
  '--danger-plain-color',
  '--warning-soft-color',
  '--warning-soft-bg-color',
  '--warning-soft-border-color',
  '--danger-tint-bg-color',
  // Round 3 — the rank-3 (bronze) badge in RaceExecution/FreeRaceExecution.
  // Ranks 1/2 already read tokens (--cub-scouting-gold, --surface-strong-
  // color); this completes the trio rather than leaving rank 3 the one
  // literal.
  '--rank-bronze-color',
  '--rank-silver-icon-color',
  '--rank-bronze-icon-color',
  // Round 4 — the "Round Progress" panel in RaceExecution.tsx.
  '--progress-panel-border-color',
  '--progress-label-color',
  '--progress-value-color',
  // Round 5 — FreeRaceExecution's own 1st-place row tint (blue, not gold —
  // free race heats use --scouting-blue rather than the gold rank fill).
  '--highlight-blue-tint-color',
  // Round 6 — TimerDiagnostics.tsx's device-provenance and last-error notes.
  '--warning-brown-color',
  '--danger-notice-bg-color',
  '--danger-notice-border-color',
];

export const DISPLAY_TOKEN_NAMES: readonly string[] = [
  '--display-bg-color',
  '--display-surface-color',
  '--display-surface-alt-color',
  '--display-text-color',
  '--display-text-muted-color',
  '--display-border-color',
  '--display-accent-color',
  '--display-overlay-bg-color',
  // Added by #501 — the identify badge/flash overlays in Observation.tsx
  // (#495) are their own distinct alpha, not the results overlay's.
  '--display-badge-bg-color',
  '--display-flash-bg-color',
  // Added by #501 — PhotoSlideshow.tsx's own three levels of muted text,
  // distinct from --display-text-muted-color.
  '--display-text-subtle-color',
  '--display-text-faint-color',
  '--display-text-faintest-color',
  // Added by #501 — Observation.tsx's projector-mode residuals.
  // --display-on-accent-color fills the gap #498's own comments flagged:
  // "there is still no 'text on Display accent' role in the vocabulary".
  '--display-highlight-gold-tint-color',
  '--display-placeholder-color',
  '--display-on-accent-color',
  '--display-text-dim-color',
  '--display-text-quiet-color',
  '--display-border-subtle-color',
  '--display-card-bg-color',
  '--display-accent-muted-color',
];

/**
 * Every Printables token name a theme may set. `--print-header-gradient-*`
 * and `--print-decor-color` are deliberately absent from six of the seven
 * themes' `tokens` maps — Newsprint is the one theme that sets
 * `--print-decor-color` (the single-ink override) and the one that omits
 * the gradient pair (its header renders as a rule, not a fill; see
 * `[data-theme="newsprint"]` in `PrintSheet.css`). Listing every name here,
 * not just the ones a given theme happens to use, is what lets `applyTheme`
 * clear a token a *previous* theme set and this one does not.
 */
export const PRINTABLES_TOKEN_NAMES: readonly string[] = [
  '--print-primary-color',
  '--print-accent-color',
  '--print-header-gradient-start',
  '--print-header-gradient-end',
  '--print-surface-color',
  '--print-text-color',
  '--print-text-muted-color',
  '--print-decor-strength',
  '--print-decor-color',
  // Round 2 (#501) — the remaining card/document neutrals PrintSheet.css
  // still hardcoded. Same value on every theme; Printables is always light
  // (see the "every Printables surface is light" test), so there is no dark
  // variant to design.
  '--print-divider-color',
  '--print-border-color',
  '--print-highlight-bg-color',
  '--print-cut-line-color',
  '--print-photo-placeholder-bg-color',
  '--print-text-secondary-color',
  '--print-label-color',
  '--print-panel-bg-color',
  '--print-muted-alt-color',
  '--print-table-border-color',
  '--print-row-alt-bg-color',
  '--print-rule-line-color',
  '--print-text-tertiary-color',
  '--print-header-subtitle-color',
];

export const DEFAULT_THEME_KEY: ThemeKey = 'field-uniform';

export const THEMES: readonly Theme[] = [
  {
    key: 'field-uniform',
    name: 'Field Uniform',
    description: 'The look Trusty Track has always had — Scouting blue and gold, unchanged.',
    occasion:
      "The reasonable default for an ordinary race day with no occasion in particular — you don't have to pick this, it's what a fresh install already shows.",
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#f5f5f5',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#f8f9fa',
        '--text-color': '#333333',
        '--text-muted-color': '#666666',
        '--border-color': '#dddddd',
        '--scouting-blue': '#003F87',
        '--cub-scouting-gold': '#FCD116',
        '--scouting-red': '#D63232',
        '--on-primary-color': '#ffffff',
        '--on-accent-color': '#003F87',
        '--focus-ring-color': '#003F87',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // Exactly today's `.projector-mode` palette, retired into token form
    // rather than redesigned (#498's stage-1 groundwork). App text
    // #333333 on #f5f5f5: 11.6:1. On-primary #ffffff on #003F87: 10.2:1.
    // Display text #ffffff on #0A0A0A: ~19:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#0A0A0A',
        '--display-surface-color': '#1a1a1a',
        '--display-surface-alt-color': '#111111',
        '--display-text-color': '#ffffff',
        '--display-text-muted-color': '#aaaaaa',
        '--display-border-color': '#333333',
        '--display-accent-color': '#FCD116',
        '--display-overlay-bg-color': 'rgba(0, 0, 0, 0.95)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // Printables text #222222 on #ffffff: ~15.9:1.
    printables: {
      isDark: false,
      printBehavior: 'as-is',
      tokens: {
        '--print-primary-color': '#003F87',
        '--print-accent-color': '#FCD116',
        '--print-header-gradient-start': '#002a5c',
        '--print-header-gradient-end': '#0b4f9e',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#222222',
        '--print-text-muted-color': '#666666',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'under-the-lights',
    name: 'Under the Lights',
    description:
      'A darker screen for the parts of the day that happen after the sun goes down — running heats with the gym lights low, or the awards ceremony that follows.',
    occasion:
      'An evening race, or any pack that dims the gym lights once the projector goes up and wants the operator’s own laptop to stop being the brightest thing in the room.',
    // `--scouting-blue` is lightened well past the brand navy (#003F87
    // would nearly vanish against a near-black background) — the same move
    // www/styles.css's own dark mode already makes. App text #eef1f6 on
    // #12161d: ~15.8:1. On-accent #0b1420 on #FCD116: ~13.6:1.
    app: {
      isDark: true,
      tokens: {
        '--background-color': '#12161d',
        '--surface-color': '#1c222c',
        '--surface-alt-color': '#242b37',
        '--text-color': '#eef1f6',
        '--text-muted-color': '#9aa7b8',
        '--border-color': '#313b4a',
        '--scouting-blue': '#5b9bd9',
        '--cub-scouting-gold': '#FCD116',
        '--scouting-red': '#ff6b6b',
        '--on-primary-color': '#0b1420',
        '--on-accent-color': '#0b1420',
        '--focus-ring-color': '#FCD116',
        '--divider-color': '#2a3140',
        '--input-border-color': '#3a4557',
        '--text-subtle-color': '#7d8ba0',
        '--text-faint-color': '#6b7789',
        '--text-placeholder-color': '#5a6578',
        '--text-quiet-color': '#8798ac',
        '--text-faintest-color': '#4d5769',
        '--text-strong-color': '#cfd6e0',
        '--text-heading-alt-color': '#b7c0cf',
        '--text-strong-muted-color': '#a3adbd',
        '--text-emphasis-color': '#f5f7fa',
        '--surface-tint-color': '#1f2531',
        '--surface-hover-color': '#232a3a',
        '--surface-soft-color': '#262d3b',
        '--surface-faint-color': '#171b23',
        '--surface-strong-color': '#2c3444',
        '--border-faint-color': '#29303e',
        '--success-color': '#6fcf7a',
        '--success-bg-color': '#16321c',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#e0c060',
        '--warning-bg-color': '#3a3018',
        '--warning-strong-color': '#d9b04a',
        '--warning-strong-bg-color': '#3a2f14',
        '--warning-strong-border-color': '#6b5723',
        '--danger-strong-color': '#e57373',
        '--danger-bg-color': '#3a1c1c',
        '--danger-border-color': '#5c2b2b',
        '--danger-accent-color': '#f4645a',
        '--info-accent-color': '#64b5f6',
        '--active-accent-color': '#ffb74d',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.6)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.85)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.78)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#6fa8ff',
        '--banner-active-bg-color': '#3a3418',
        '--banner-success-bg-color': '#17301c',
        '--banner-success-color': '#7fd88a',
      },
    },
    // The same darkness the App surface now shares, taken all the way to
    // today's projector black — nobody is reading fine print off a
    // projector. Display text #ffffff on #0A0A0A: ~19:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#0A0A0A',
        '--display-surface-color': '#1a1a1a',
        '--display-surface-alt-color': '#111111',
        '--display-text-color': '#ffffff',
        '--display-text-muted-color': '#aaaaaa',
        '--display-border-color': '#333333',
        '--display-accent-color': '#FCD116',
        '--display-overlay-bg-color': 'rgba(0, 0, 0, 0.95)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // Lightened: a dark app and a dark projector do not argue for a dark
    // pit pass — the ink bill is the same regardless of what time the race
    // runs. The palette shifts cooler to read as "the same event, at
    // night." Printables text #1a1a1a on #ffffff: ~17.4:1.
    printables: {
      isDark: false,
      printBehavior: 'lightened',
      printNote:
        'The paper stays light — a dark screen does not mean a dark pit pass — but the palette shifts cooler, to read as the same event at night.',
      tokens: {
        '--print-primary-color': '#0b1420',
        '--print-accent-color': '#B9C6D6',
        '--print-header-gradient-start': '#05080d',
        '--print-header-gradient-end': '#16283f',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#1a1a1a',
        '--print-text-muted-color': '#5a5a5a',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'old-glory',
    name: 'Old Glory',
    description: 'Red, white, and blue, for a derby run on a patriotic theme.',
    occasion:
      "Packs running a patriotic-themed derby — common around Presidents' Day — where the pit passes, the standings, and the trophy slide should look like the rest of the room's decorations.",
    // The accent role token carries the flag red here instead of gold —
    // "the accent color," not literally gold, under this theme. App text
    // #1a1a1a on #f7f7f5: ~16.1:1. On-accent #ffffff on #B31942: ~6.7:1.
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#f7f7f5',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#eef2f6',
        '--text-color': '#1a1a1a',
        '--text-muted-color': '#5a5a5a',
        '--border-color': '#d8d8d8',
        '--scouting-blue': '#0A3161',
        '--cub-scouting-gold': '#B31942',
        '--scouting-red': '#D63232',
        '--on-primary-color': '#ffffff',
        '--on-accent-color': '#ffffff',
        '--focus-ring-color': '#0A3161',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // Rejected: red heading text on the navy background — Old Glory Red on
    // #0A1E3D measures ~2.5:1, under the 3:1 large-text floor. Red survives
    // only as a fill behind white text (a record-break banner, a highlight
    // chip), never as running text on navy; headings keep the gold that
    // already proved out on `.projector-mode` (~11.3:1 here). Display text
    // #ffffff on #0A1E3D: ~16.6:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#0A1E3D',
        '--display-surface-color': '#142A4D',
        '--display-surface-alt-color': '#0d213b',
        '--display-text-color': '#ffffff',
        '--display-text-muted-color': '#b7c4d6',
        '--display-border-color': '#24406b',
        '--display-accent-color': '#FCD116',
        '--display-overlay-bg-color': 'rgba(10, 30, 61, 0.95)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // As-is: a navy header band and a red rule cost about the same ink as
    // Field Uniform's navy-and-gold. The licence security wash and the
    // pit-pass portrait ring use the accent (red) in place of gold.
    // Printables text #1a1a1a on #ffffff: ~17.4:1.
    printables: {
      isDark: false,
      printBehavior: 'as-is',
      tokens: {
        '--print-primary-color': '#0A3161',
        '--print-accent-color': '#B31942',
        '--print-header-gradient-start': '#06213f',
        '--print-header-gradient-end': '#123a6b',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#1a1a1a',
        '--print-text-muted-color': '#5a5a5a',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'clear-sight',
    name: 'Clear Sight',
    description:
      'Bigger, bolder, and unmistakable from across the room — for a gym where the projector fights the daylight, or for anyone who wants the screens easier to read.',
    occasion:
      'A venue with harsh overhead fluorescents or a projector competing with windows, or a volunteer at check-in who finds the default text small or the colors low-contrast. Legibility first, everything else second.',
    // Rejected: the literal gold, #FCD116, as an accent role — used as text
    // or a thin line it measures 1.47:1 against white. Deepened to a true
    // amber (#8A5A00, ~5.2:1) and standardized on white as the on-accent
    // color everywhere. App text #000000 on #ffffff: 21:1 (the strongest of
    // the seven). On-accent #ffffff on #8A5A00: ~5.2:1.
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#ffffff',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#f0f0f0',
        '--text-color': '#000000',
        '--text-muted-color': '#3d3d3d',
        '--border-color': '#000000',
        '--scouting-blue': '#002357',
        '--cub-scouting-gold': '#8A5A00',
        '--scouting-red': '#a6192e',
        '--on-primary-color': '#ffffff',
        '--on-accent-color': '#ffffff',
        '--focus-ring-color': '#000000',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // The literal gold that the App surface had to deepen is reinstated
    // here: it recedes on white paper but a vivid gold on true black
    // measures ~16.7:1, the theme's strongest pairing. Display text
    // #ffffff on #000000: 21:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#000000',
        '--display-surface-color': '#000000',
        '--display-surface-alt-color': '#000000',
        '--display-text-color': '#ffffff',
        '--display-text-muted-color': '#d9d9d9',
        '--display-border-color': '#ffffff',
        '--display-accent-color': '#FCD116',
        '--display-overlay-bg-color': 'rgba(0, 0, 0, 1)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // As-is, and the theme most robust to being photocopied — no mid-tone
    // greys anywhere for a fourth-generation copy to lose. Printables text
    // #000000 on #ffffff: 21:1.
    printables: {
      isDark: false,
      printBehavior: 'as-is',
      tokens: {
        '--print-primary-color': '#002357',
        '--print-accent-color': '#8A5A00',
        '--print-header-gradient-start': '#001233',
        '--print-header-gradient-end': '#002357',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#000000',
        '--print-text-muted-color': '#3d3d3d',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'sawdust-and-pine',
    name: 'Sawdust & Pine',
    description: 'Warm, wood-toned, and a little more like a keepsake than a spreadsheet.',
    occasion:
      'A banquet night where the certificates are meant to be framed, or a milestone-anniversary derby where "handmade in the garage" is the right feeling. The palette extends the cream/wood tones the project’s own marketing site already uses.',
    // The primary role token trades navy for a workshop brown; gold is left
    // exactly as the default, since gold-beside-wood is already a natural
    // pairing. App text #2b2118 on #FDF8EE: ~14.4:1. On-primary #FDF8EE on
    // #5C3B21: ~9.1:1.
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#FDF8EE',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#F5EEDD',
        '--text-color': '#2b2118',
        '--text-muted-color': '#6b5c48',
        '--border-color': '#E4D9C0',
        '--scouting-blue': '#5C3B21',
        '--cub-scouting-gold': '#FCD116',
        '--scouting-red': '#D63232',
        '--on-primary-color': '#FDF8EE',
        '--on-accent-color': '#2b2118',
        '--focus-ring-color': '#5C3B21',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // A warm dark rather than a cold one: the App surface's near-white
    // background inverts to near-black, and warm off-white text (not stark
    // white) keeps the "workshop lamp" feeling once the lights come down.
    // Display text #FBF2E1 on #1C130B: ~18:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#1C130B',
        '--display-surface-color': '#2A1D10',
        '--display-surface-alt-color': '#150E07',
        '--display-text-color': '#FBF2E1',
        '--display-text-muted-color': '#C7B79C',
        '--display-border-color': '#4a341f',
        '--display-accent-color': '#FCD116',
        '--display-overlay-bg-color': 'rgba(15, 9, 4, 0.95)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // As-is — this theme's real reason to exist: a certificate that reads
    // as a keepsake rather than a corporate form. Printables text #2b2118
    // on #FFFDF7: ~14.3:1.
    printables: {
      isDark: false,
      printBehavior: 'as-is',
      tokens: {
        '--print-primary-color': '#5C3B21',
        '--print-accent-color': '#FCD116',
        '--print-header-gradient-start': '#3c2513',
        '--print-header-gradient-end': '#6b4527',
        '--print-surface-color': '#FFFDF7',
        '--print-text-color': '#2b2118',
        '--print-text-muted-color': '#6b5c48',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'trail-colors',
    name: 'Trail Colors',
    description: "Green and gold-orange, for a day that's more about fun than formality.",
    occasion:
      'A pack fun day, a Lion/Tiger-heavy racingGroup’s first derby, or any pack that finds the corporate navy-and-gold a little stiff for a Saturday morning with juice boxes.',
    // Both role tokens move away from the corporate navy/lemon pairing
    // toward warmer, more natural hues. App text #23301F on #F4F7F1:
    // ~14:1. On-primary #ffffff on #2F6B3A: ~6.4:1. On-accent #2b1c05 on
    // #F2A93B: ~8.3:1.
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#F4F7F1',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#E9F0E3',
        '--text-color': '#23301F',
        '--text-muted-color': '#5C6E54',
        '--border-color': '#D3E0C9',
        '--scouting-blue': '#2F6B3A',
        '--cub-scouting-gold': '#F2A93B',
        '--scouting-red': '#D63232',
        '--on-primary-color': '#ffffff',
        '--on-accent-color': '#2b1c05',
        '--focus-ring-color': '#2F6B3A',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // A dark forest-night green rather than the default's neutral black.
    // Display accent #F2A93B on #0E1810: ~9.1:1.
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#0E1810',
        '--display-surface-color': '#1B2A1F',
        '--display-surface-alt-color': '#0A130C',
        '--display-text-color': '#F4F7F1',
        '--display-text-muted-color': '#B9C7B2',
        '--display-border-color': '#2E4530',
        '--display-accent-color': '#F2A93B',
        '--display-overlay-bg-color': 'rgba(14, 24, 16, 0.95)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // As-is; a green header band and an orange rule cost the same ink
    // class as the default. Printables text #23301F on #ffffff: ~14:1.
    printables: {
      isDark: false,
      printBehavior: 'as-is',
      tokens: {
        '--print-primary-color': '#2F6B3A',
        '--print-accent-color': '#F2A93B',
        '--print-header-gradient-start': '#1f4d29',
        '--print-header-gradient-end': '#3f8a4c',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#23301F',
        '--print-text-muted-color': '#5C6E54',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '1',
      },
    },
  },
  {
    key: 'newsprint',
    name: 'Newsprint',
    description:
      'Black ink on white paper, with almost nothing else — built for a pack printing sixty pit passes on a home inkjet that’s already running low.',
    occasion:
      'Tight print budgets. Every other theme’s printables cost roughly the same ink as the default; this is the one built specifically to cost less.',
    // Rejected: black text on the masthead red — the obvious pairing
    // measures ~3.1:1 against #B31B1B, under the 4.5:1 floor. On-accent is
    // white instead (~6.8:1); on-primary and on-accent end up the same
    // value here, which is fine. App text #000000 on #ffffff: 21:1.
    app: {
      isDark: false,
      tokens: {
        '--background-color': '#ffffff',
        '--surface-color': '#ffffff',
        '--surface-alt-color': '#f2f2f2',
        '--text-color': '#000000',
        '--text-muted-color': '#4d4d4d',
        '--border-color': '#000000',
        '--scouting-blue': '#000000',
        '--cub-scouting-gold': '#B31B1B',
        '--scouting-red': '#B31B1B',
        '--on-primary-color': '#ffffff',
        '--on-accent-color': '#ffffff',
        '--focus-ring-color': '#B31B1B',
        '--divider-color': '#eeeeee',
        '--input-border-color': '#cccccc',
        '--text-subtle-color': '#888888',
        '--text-faint-color': '#999999',
        '--text-placeholder-color': '#bbbbbb',
        '--text-quiet-color': '#777777',
        '--text-faintest-color': '#aaaaaa',
        '--text-strong-color': '#222222',
        '--text-heading-alt-color': '#444444',
        '--text-strong-muted-color': '#555555',
        '--text-emphasis-color': '#000000',
        '--surface-tint-color': '#f9f9f9',
        '--surface-hover-color': '#f0f7ff',
        '--surface-soft-color': '#f0f0f0',
        '--surface-faint-color': '#fafafa',
        '--surface-strong-color': '#e0e0e0',
        '--border-faint-color': '#e4e4e4',
        '--success-color': '#2e7d32',
        '--success-bg-color': '#e8f5e9',
        '--success-accent-color': '#4caf50',
        '--warning-color': '#8a6d00',
        '--warning-bg-color': '#fff8e1',
        '--warning-strong-color': '#7a5b00',
        '--warning-strong-bg-color': '#fff3cd',
        '--warning-strong-border-color': '#ffe08a',
        '--danger-strong-color': '#c62828',
        '--danger-bg-color': '#ffebee',
        '--danger-border-color': '#ffcdd2',
        '--danger-accent-color': '#f44336',
        '--info-accent-color': '#2196f3',
        '--active-accent-color': '#ff9800',
        '--overlay-backdrop-color': 'rgba(0, 0, 0, 0.5)',
        '--overlay-backdrop-soft-color': 'rgba(0, 0, 0, 0.4)',
        '--overlay-backdrop-strong-color': 'rgba(0, 0, 0, 0.8)',
        '--overlay-backdrop-demo-color': 'rgba(0, 0, 0, 0.72)',
        '--scouting-blue-hover-color': '#002d6b',
        '--table-row-hover-color': '#f8faff',
        '--highlight-card-bg-color': '#f7f9fc',
        '--record-highlight-bg-color': '#fffaf0',
        '--neutral-accent-color': '#9e9e9e',
        '--running-accent-color': '#673ab7',
        '--hardware-connect-color': '#4a148c',
        '--hardware-connect-hover-color': '#6a1b9a',
        '--danger-accent-bg-color': '#ffeeee',
        '--caution-bg-color': '#fff3e0',
        '--caution-text-color': '#e65100',
        '--caution-border-color': '#ffe0b2',
        '--caution-icon-color': '#f57c00',
        '--warning-alt-border-color': '#ffe082',
        '--info-panel-bg-color': '#e3f2fd',
        '--info-panel-border-color': '#90caf9',
        '--info-notice-bg-color': '#f3f6fb',
        '--warning-notice-border-color': '#f0d98c',
        '--warning-notice-text-color': '#5b4a00',
        '--highlight-gold-tint-color': 'rgba(252, 209, 22, 0.1)',
        '--selection-accent-color': '#3b82f6',
        '--accent-blue-color': '#2563eb',
        '--accent-blue-bg-color': '#eff6ff',
        '--accent-blue-strong-color': '#1d4ed8',
        '--accent-blue-emphasis-color': '#1e3a8a',
        '--wizard-heading-color': '#111827',
        '--wizard-text-color': '#374151',
        '--wizard-text-muted-color': '#6b7280',
        '--wizard-text-subtle-color': '#4b5563',
        '--wizard-border-color': '#e5e7eb',
        '--wizard-border-muted-color': '#d1d5db',
        '--wizard-icon-muted-color': '#9ca3af',
        '--wizard-surface-alt-color': '#f9fafb',
        '--wizard-chip-bg-color': '#f3f4f6',
        '--surface-removed-color': '#f2f2f2',
        '--danger-soft-bg-color': '#ffe6e6',
        '--preview-border-color': '#dfe3e8',
        '--progress-track-color': '#e6e6e6',
        '--attention-accent-color': '#ef6c00',
        '--neutral-info-color': '#78909c',
        '--info-highlight-bg-color': '#e6f1fb',
        '--info-highlight-border-color': '#85b7eb',
        '--warning-alt-color': '#8a6d3b',
        '--danger-faint-bg-color': '#fff5f5',
        '--danger-plain-color': '#cc0000',
        '--warning-soft-color': '#8a5a00',
        '--warning-soft-bg-color': '#fff4d6',
        '--warning-soft-border-color': '#e6c66e',
        '--danger-tint-bg-color': '#fff0f0',
        '--rank-bronze-color': '#d7a48d',
        '--rank-silver-icon-color': '#757575',
        '--rank-bronze-icon-color': '#8d6e63',
        '--progress-panel-border-color': '#e9ecef',
        '--progress-label-color': '#6c757d',
        '--progress-value-color': '#495057',
        '--highlight-blue-tint-color': 'rgba(0, 63, 135, 0.05)',
        '--warning-brown-color': '#5d4037',
        '--danger-notice-bg-color': '#fdecea',
        '--danger-notice-border-color': '#f5c6c3',
        '--link-color': '#1a73e8',
        '--banner-active-bg-color': '#fffbea',
        '--banner-success-bg-color': '#f0f9f0',
        '--banner-success-color': '#256029',
      },
    },
    // A light App theme still cannot go on a projector as-is; it inverts
    // to black like every other theme here. The accent brightens from the
    // App surface's ink-conscious masthead red to a more saturated
    // red-orange, since a color chosen to survive as printed text is not
    // the same color a projector 40 feet away needs as a headline accent.
    // Display accent #E5484D on #000000: ~5.5:1 (short callout text only).
    display: {
      isDark: true,
      tokens: {
        '--display-bg-color': '#000000',
        '--display-surface-color': '#111111',
        '--display-surface-alt-color': '#000000',
        '--display-text-color': '#ffffff',
        '--display-text-muted-color': '#cccccc',
        '--display-border-color': '#ffffff',
        '--display-accent-color': '#E5484D',
        '--display-overlay-bg-color': 'rgba(0, 0, 0, 0.97)',
        '--display-badge-bg-color': 'rgba(0, 0, 0, 0.75)',
        '--display-flash-bg-color': 'rgba(0, 0, 0, 0.88)',
        '--display-text-subtle-color': '#cccccc',
        '--display-text-faint-color': '#dddddd',
        '--display-text-faintest-color': '#888888',
        '--display-highlight-gold-tint-color': 'rgba(212, 175, 55, 0.1)',
        '--display-placeholder-color': '#666666',
        '--display-on-accent-color': '#000000',
        '--display-text-dim-color': '#bbbbbb',
        '--display-text-quiet-color': '#777777',
        '--display-border-subtle-color': '#555555',
        '--display-card-bg-color': '#222222',
        '--display-accent-muted-color': '#999999',
      },
    },
    // Lightened, ink-minimal: no second spot color at all — accent equals
    // primary, both black, so a strictly monochrome laser never renders
    // one as a muddy grey. The header's filled gradient is not set at all
    // (see `[data-theme="newsprint"]` in `PrintSheet.css` — the header
    // renders as a rule, not a fill). `--print-decor-strength: 0.12`
    // fades the chequered band, the licence's security wash and the
    // certificate's guilloche to about a tenth of their default opacity —
    // the discrete ornaments (corner flourish, rosette, derby car) are
    // NOT governed by this and stay full black. Printables text #000000
    // on #ffffff: 21:1.
    printables: {
      isDark: false,
      printBehavior: 'lightened',
      printNote:
        'No second ink color, and the decoration fades to about a tenth of its usual weight — this theme exists to cost less toner, not to look different for its own sake.',
      tokens: {
        '--print-primary-color': '#000000',
        '--print-accent-color': '#000000',
        '--print-surface-color': '#ffffff',
        '--print-text-color': '#000000',
        '--print-text-muted-color': '#4d4d4d',
        '--print-divider-color': '#eeeeee',
        '--print-border-color': '#dddddd',
        '--print-highlight-bg-color': '#f0f7ff',
        '--print-cut-line-color': '#bbbbbb',
        '--print-photo-placeholder-bg-color': '#eef2f7',
        '--print-text-secondary-color': '#333333',
        '--print-label-color': '#444444',
        '--print-panel-bg-color': '#f7faff',
        '--print-muted-alt-color': '#7a8899',
        '--print-table-border-color': '#b9c3cf',
        '--print-row-alt-bg-color': '#f2f6fb',
        '--print-rule-line-color': '#c8d2de',
        '--print-text-tertiary-color': '#555555',
        '--print-header-subtitle-color': 'rgba(255, 255, 255, 0.85)',
        '--print-decor-strength': '0.12',
        '--print-decor-color': '#000000',
      },
    },
  },
];

/** A theme by key, or Field Uniform if the key is unrecognised — an old
 *  device/install holding a key from a build that renamed or dropped a
 *  theme falls back to the default rather than rendering nothing. */
export function themeByKey(key: string): Theme {
  return THEMES.find((t) => t.key === key) ?? THEMES.find((t) => t.key === DEFAULT_THEME_KEY)!;
}

/** Every key this build ships, for the picker and for validating a stored
 *  value. */
export const THEME_KEYS: readonly ThemeKey[] = THEMES.map((t) => t.key);
