#!/usr/bin/env bash
#
# Builds the whole of trusty-track.com into one directory:
#
#   dist/           the landing page, copied verbatim from www/
#   dist/docs/      the mkdocs site
#
# The two are one deployment on purpose. The landing page links into the guides
# constantly, and the guides link back; on separate hosts every one of those is
# a cross-origin hop that has to be kept in step by hand. It also means the
# landing page can reference `/docs/assets/...` for the logo and the
# screenshots rather than keeping a second copy of them — those images are
# generated by the Playwright specs in frontend/e2e/docs/, and a copy would go
# stale the first time somebody regenerated one.
#
# Usage: scripts/build_site.sh [output-dir]
#
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="${1:-dist}"

# `mkdocs` is on PATH in the Cloudflare Pages build image (pip installs it from
# docs/requirements.txt); locally it lives in the uv environment.
if command -v mkdocs >/dev/null 2>&1; then
  MKDOCS=(mkdocs)
else
  MKDOCS=(uv run mkdocs)
fi

rm -rf "$OUT"

# --strict turns a broken link or a missing image into a failed build. Without
# it mkdocs warns and publishes anyway, and nobody reads a green job's log.
"${MKDOCS[@]}" build --strict --site-dir "$OUT/docs"

# `www/.` rather than `www/*` so the dotfiles come too — _headers, _redirects
# and robots.txt are all Cloudflare Pages configuration that lives in there.
cp -R www/. "$OUT/"

echo
echo "Built $OUT/"
echo "  landing page : $OUT/index.html"
echo "  docs         : $OUT/docs/index.html"
echo
echo "Preview it with:  python3 -m http.server -d $OUT 8080"
