"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-24 22:56:22.331709

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: groups.debug_mode is deliberately absent here and added in 0002.
    # Databases created before Alembic was adopted may or may not have that
    # column, depending on whether the old hand-rolled ALTER in init_db() ran.
    # Baselining without it lets both variants be stamped at this revision and
    # then reconciled by 0002, which checks before adding.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_groups_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_groups_name"), ["name"], unique=True)

    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lane_count", sa.Integer(), nullable=False),
        sa.Column("length_feet", sa.Integer(), nullable=True),
        sa.Column(
            "timer_type",
            sa.Enum(
                "FAKE", "AUTO_DETECT_BACKEND", "AUTO_DETECT_PROXY", name="timertype"
            ),
            nullable=False,
        ),
        sa.Column("serial_port", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracks_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_name"), ["name"], unique=False)

    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date_time", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column(
            "car_numbering_strategy",
            sa.Enum("PER_GROUP", "GLOBAL", "MANUAL", name="carnumberingstrategy"),
            nullable=False,
        ),
        sa.Column("global_start_number", sa.Integer(), nullable=False),
        sa.Column("championship_trophies", sa.Integer(), nullable=False),
        sa.Column(
            "scoring_strategy",
            sa.Enum("TIMED", "POINTS", name="scoringstrategy"),
            nullable=False,
        ),
        sa.Column("rules_configuration", sa.String(), nullable=True),
        sa.Column("auto_advance_heat", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_races_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_races_name"), ["name"], unique=True)

    op.create_table(
        "dens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column(
            "rank",
            sa.Enum(
                "LION",
                "TIGER",
                "WOLF",
                "BEAR",
                "WEBELOS",
                "ARROW_OF_LIGHT",
                "OTHER",
                name="rank",
            ),
            nullable=True,
        ),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("car_number_range_start", sa.Integer(), nullable=True),
        sa.Column("car_number_range_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dens_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dens_name"), ["name"], unique=False)

    op.create_table(
        "free_race_heats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("lane_assignments", sa.String(), nullable=False),
        sa.Column("lane_results", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("free_race_heats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_free_race_heats_id"), ["id"], unique=False)

    op.create_table(
        "racing_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("den_id", sa.Integer(), nullable=True),
        sa.Column("car_number_range_start", sa.Integer(), nullable=True),
        sa.Column("car_number_range_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["den_id"],
            ["dens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("racing_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_racing_groups_id"), ["id"], unique=False)

    op.create_table(
        "rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "scheduling_strategy",
            sa.Enum("PPC", name="schedulingstrategy"),
            nullable=False,
        ),
        sa.Column("advancement_source", sa.String(), nullable=True),
        sa.Column("advancement_num_racers", sa.Integer(), nullable=True),
        sa.Column("den_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["den_id"],
            ["dens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rounds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rounds_id"), ["id"], unique=False)

    op.create_table(
        "heats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("heat_number", sa.Integer(), nullable=False),
        sa.Column("lane_results", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_heats_id"), ["id"], unique=False)

    op.create_table(
        "racers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("car_number", sa.Integer(), nullable=True),
        sa.Column("car_name", sa.String(), nullable=True),
        sa.Column("car_passed_inspection", sa.Boolean(), nullable=False),
        sa.Column("car_weight", sa.Float(), nullable=True),
        sa.Column("racer_image_url", sa.String(), nullable=True),
        sa.Column("car_image_url", sa.String(), nullable=True),
        sa.Column("racing_group_id", sa.Integer(), nullable=True),
        sa.Column("den_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["den_id"],
            ["dens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["racing_group_id"],
            ["racing_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("racers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_racers_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("racers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_racers_id"))

    op.drop_table("racers")
    with op.batch_alter_table("heats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_heats_id"))

    op.drop_table("heats")
    with op.batch_alter_table("rounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rounds_id"))

    op.drop_table("rounds")
    with op.batch_alter_table("racing_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_racing_groups_id"))

    op.drop_table("racing_groups")
    with op.batch_alter_table("free_race_heats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_free_race_heats_id"))

    op.drop_table("free_race_heats")
    with op.batch_alter_table("dens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dens_name"))
        batch_op.drop_index(batch_op.f("ix_dens_id"))

    op.drop_table("dens")
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_races_name"))
        batch_op.drop_index(batch_op.f("ix_races_id"))

    op.drop_table("races")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_name"))
        batch_op.drop_index(batch_op.f("ix_tracks_id"))

    op.drop_table("tracks")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_name"))
        batch_op.drop_index(batch_op.f("ix_groups_id"))

    op.drop_table("groups")
    # ### end Alembic commands ###
