"""Intermission highlights: races.intermission_highlights (#177 stage 3).

Revision ID: 0058_intermission_highlights
Revises: 0057_stored_replay_clips
Create Date: 2026-09-16 17:44:22.690614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0058_intermission_highlights"
down_revision: str | Sequence[str] | None = "0057_stored_replay_clips"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "intermission_highlights",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.drop_column("intermission_highlights")

    # ### end Alembic commands ###
